#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.1": *
#show: codly-init.with()
#set page(
  paper: "a5",
  margin: (x: 1.8cm, y: 1.5cm),
)
#set text(
  font: "New Computer Modern",
  size: 10pt,
)
#set par(
  justify: true,
  leading: 0.52em,
)

#show title: set text(size: 20pt)
#show title: set align(center)

#title[
  #text(size: 32pt, weight: "bold")[simple-ring]
  #v(0.1em)
  #text(size: 14pt, fill: luma(30%))[\
  Mathematical Primitives for Lattice-Based Cryptography]
  #v(0.7em)
  #text(size: 11pt, fill: luma(40%), style: "italic")[\
  An Educational Implementation for Learning and Experimentation]
]


\
#outline(title: [Table of contents])
\
#pagebreak()
= Introduction
\
#emph[This document describes simple-ring, an educational implementation of
mathematical primitives for lattice-based cryptography.]

Modern post-quantum cryptography (BFV, CKKS, Kyber, Dilithium) relies on the
polynomial ring $R_q = ZZ_q [X] slash (X^n + 1)$. Understanding this structure
is essential for working with these schemes, but research papers are often complicated, and are often not written for educational purposes, especially in Rust.

#strong[Goal:] Bridge the gap between abstract mathematics and concrete implementation.

== Warning
\
Before everything, I wanted to warn you about the security of this code. This code *isn't* audited, *isn't* made to be used seriously, *is* vulnerable to timing-based attacks...
\
So please don't use it in vulnerable environments. But, you can use it to experiment with schemes, you can re-use the NTT, the polynomial code... as you want.
\
Make everything you imagine with it, but *don't* use it with sensitive data.
\

== What's inside ?
\
`simple-ring` provides:
\
\
+ Polynomials in $ZZ_q$,
+ NTT/INTT for fast multiplication,
+ Modular arithmetic,
+ Sampling methods (CBD, Uniform)



== How to read it ?
\
This documentation revolves around the structure of the crate, and a "progression". First, we'll introduce mathematical basics, then will explain the Rust code; in details.
\
#pagebreak()

= `ring.rs` : The Ring
\
== Congruence
\
First, let's introduce mathematical basics. The symbol "$equiv$" means "is congruent to" ("est congru à" in french), which means :
\
#align(center)[$a equiv b (mod n) arrow.l.r.double (a mod n) = (b mod n)$]
\
For example, if we have $a = 5$, $b = 17$, $q = 12$ :
\
#align(center)[$a mod q = 5 mod 12 = 5$]
#align(center)[$b mod q = 17 mod 12 = 5$]
\
So $a equiv b mod q$.
\
\
== What is a Ring ?
\
A ring is a mathematical structure where you can :
\
\
+ Add elements (integers for example),
+ Subtract elements (addition has inverses),
+ Multiply elements (distributive over additions)
\
Think of it as a structure where you can define operations and rules.

The formal definition of a commutative ring is a set $R$ equipped with two operations : addition and multiplication.
#table(
  columns: 3,
  [*Property*], [*Addition*], [*Multiplication*],
  [Closure], [$a + b in R$], [$a * b in R$],
  [Assiociativity], [$(a+b)+c = a+(b+c)$], [$(a*b) * c = (b*c)*a$],
  [Identity], [$exists 0, a + 0 = a$], [$exists 1, a * 1 = a$],
  [Inverses], [$forall a, exists -a, a + (-a) = 0$], [Not always],
  [Commutativity], [$a + b = b + a$], [$a * b = b * a$],
  [Distributivity], [], [$a * (b + c) = a * c + a * b$],
)

If the multiplication is not commutative, it's a *non-commutative ring*. If there's no multiplicative identity, it's a *pseudo-ring*, and not a ring.
\
\
== The ring used in cryptography
\
In lattice-based cryptography, such as *BFV* or *Kyber*, all the computations are done in a commutative ring. It is noted as :
#align(center)[$ZZ_q [X]slash(X^n+1)$]
Where :
\

$ZZ_q$ is a set of integers ${0, 1, 2, ..., q -1}$ with arithmetic performed modulo $q$. $ZZ_q$ is always a finite commutative ring with $q$ elements. 
If $q$ is prime, $ZZ_q$ is additionally a #strong[field] (every non-zero element has a multiplicative inverse). In the code, all the coefficients are reduced modulo $q$ after each operation.
\

$[X]$ is the polynomial ring construction : $ZZ_q [X]$ denotes the set of all polynomials whose coefficients belong to $ZZ_q$. (The form of the polynomial is $a(x) = a_0X⁰ + a_1X¹ + ... + a_k X^k$ where $a_i in ZZ_q$).
\

Finally, we quotient by the ideal generated by $(X^n + 1)$. In the quotient ring, we have the equality $X^n equiv -1$. It is useful, because any polynomial of degree $>= n$ is reduced to a polynomial of degree $< n$ by repeatedly substituting $X^n$ with -1.
\
\
In our Rust code, we implement a structure for the ring :

#codly(languages: codly-languages)
```rust
//ring.rs
#[derive(Clone)]
pub struct RingParams {
    pub n: usize, //The length of the polynomial, in usize.
    pub q: u64, //The modulus
    pub omega: u64, //omega, for the NTT (we'll see it in ntt.rs)
}
impl RingParams { 
    pub fn new(n: usize, q:u64, omega: u64) -> Self {
        Self { n, q, omega }
    }
}
```

#pagebreak()

= `polys.rs` : The polynomials in $ZZ_q [X]slash(X^n+1)$
\
In `simple-ring`, the polynomials "live" in the ring. To implement polynomials in Rust, we simply create a struct `Polynomial` which contains a `Box` of an array of u64s :

#codly(languages: codly-languages)
```rust
pub struct Polynomial {
    pub coeffs: Box<[u64]>,
}

impl Polynomial {
    pub fn new(c: Vec<u64>) -> Self { 
        Self { coeffs: c.into_boxed_slice() }
    }

    pub fn zeros(n: usize) -> Self {
        Self { coeffs: vec![0u64; n].into_boxed_slice() }
    }
}
```

The `new` function allows you to create a polynomial from a `Vec<u64>`, while the `zeros` function allows you to create an empty polynomial of length $n$, $n$ being the value stored in `RingParams`.

== Polynomial operations
\
Now that we have a basic type for the polynomials, we can implement methods for basic polynomial operations, which will be useful when implenting cryptographic schemes.

=== Polynomial sum
\
The most simple operation to implement is the polynomial sum in $ZZ_q [X]slash(X^n+1)$. The sum is defined by :
\
#align(center)[$S_k = A_k + B_k mod q$]
\
Where $A$ and $B$ are two polynomials and $S$ is their sum.
\
We can easily code it, with this simple function :
\
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    fn polynomial_sum_single(params: &RingParams, first: &Self, second: &Self) -> Self { //The single-thread sum.
        let mut coeffs = vec![0u64; params.n];
        for i in 0..params.n {
            coeffs[i] = ((first.coeffs[i] as u128 + second.coeffs[i] as u128) % params.q as u128) as u64;
        }
        Polynomial::new(coeffs)
    }
}
```
In this code, we implement, for the struct _Polynomial_, the function _polynomial_sum_single_ which does the sum of two polynomials, and then represent their coefficient modulo $q$ in $ZZ_q$. Yes, I could have done something like coeffs[i].wrapping_add(...), or do something like .iter().zip(...) but it is less readable than the simple "+" operator, and the goal is here to provide a simple and readable code.
\
\
In this crate, I also wanted to implement a parallelized code. So, I used the crate `rayon`, and create a function called _polynomial_sub_multi_ which does gives exactly the same result as the _polynomial_sum_single_; but theorically more faster. In fact, I didn't notice any difference in term of performances (and sometimes the parallelized version was worst than the single-thread one). Anyway, there is the code for the parallel version : 
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[cfg(feature = "parallel")]
    fn polynomial_sum_multi(params: &RingParams, first: &Self, second: &Self) -> Self { 
        let mut coeffs = vec![0u64; params.n];
        coeffs
            .par_iter_mut() //I use the parallelized iter, provided by rayon.
            .enumerate()
            .for_each(|(i, coeff)| {
                *coeff = ((first.coeffs[i] as u128 + second.coeffs[i] as u128) % params.q as u128) as u64;
            });
        Self { coeffs: coeffs.into_boxed_slice() }
    }
}
```
=== Polynomial subtraction
\
The polynomial subtraction, in our ring, is noted as :
#align(center)[$S_k = A_k - B_k mod q$]
\
So it's slightly the same thing as the sum. We write it in Rust :
```rust
#[inline]
fn polynomial_sub_single(params: &RingParams, first: &Self, second: &Self) -> Self {
    let mut coeffs = vec![0u64; params.n];
    for i in 0..params.n {
        coeffs[i] = ((first.coeffs[i] as i128 - second.coeffs[i] as i128).rem_euclid(params.q as i128)) as u64 ; //We convert into i128 so that we don't have an underflow. The rem_euclid makes the result remain euclidean, so that it is in the ring.
    }
    Polynomial::new(coeffs)
}
```
Here, the only thing to be aware of is the fact that u64 - u64 can underflow, so that we need to convert it into i128s before computing. Also, because the result of u64 - u64 can be negative, we need to compute .rem_euclid() and not %, so that the result remains euclidean (remains positive).
Like for the polynomial sum, I've also implemented a multi-thread function :
```rust
impl Polynomial {
    [cfg(feature = "parallel")]
    fn polynomial_sub_multi(params: &RingParams, first: &Self, second: &Self) -> Self { 
        let mut coeffs = vec![0u64; params.n];
        coeffs.par_iter_mut().enumerate().for_each(|(i, coeff)| {
            *coeff = (first.coeffs[i] as i128 - second.coeffs[i] as i128).rem_euclid(params.q as i128) as u64;
        });

        Self { coeffs: coeffs.into_boxed_slice() }
    }
}
```
\

=== Polynomial multiplication <poly_mul>
\
Now, let's introduce a more "complex" function : the polynomial multiplication in $ZZ_q$.
The naive multiplication (not in the  ring) in noted as :
\
#align(center)[$M_k = sum_(i+j=k) A_i *B_j$]
\
Where $A, B$ are two polynomials and $M$ their product. Note that $A$ and $B$ should have exactly the same length.
\
So, let's implement it !
#codly(languages: codly-languages)
```rust
impl Polynomial {
    pub fn polynomial_mul(params: &RingParams, first: &Self, second: &Self) -> Self {
        assert_eq!(first.coeffs.len(), params.n); //We ensure the polynomials have the good length, and that they also have the same length.
        assert_eq!(second.coeffs.len(), params.n);

        let mut b = vec![0u64; 2 * params.n - 2]; //We create a vec, but two times larger (because the product of two polynomials have (2 * n - 2) coefficients.)

        for i in 0..params.n {
            for j in 0..params.n {
                let k = i + j;
                b[k] += first.coeffs[i] * second.coeffs[j];
            }
        }
      Self { coeffs: b.into_boxed_slice() }
}
```
\
This "naive" implementation could be good for a simple polynomial multiplication, but doesn't work for our multiplication in the ring. Also, if $n, q$ are too large, we can have an overflow. So, here are the solutions :
+ To avoid the overflow, we'll simply use u128 and not u64.
+ To have coefficients in the ring, we just reduce them mod q.
+ But the degree of the result of the multiplication doubles, so we get up to 2n−2. It means that the result isn't in $ZZ[x] slash (X^n + 1)$. For example, let's have a polynomial $b_(n+k)X^(n+k)$.
This polynomial goes has this form :
#align(center)[$P(x) = b_0X^0 + b_1X^1 + b_2X^2 + ... + b_(n+k)X^(n+k)$]
\
Where $k$ coefficients are "out" of the ring. Here is how to get them back into it :
\
\
We use the fact that :
\
#align(center)[$X^n + 1 = 0$]
\
#align(center)[$X^n = -1$]
\
So :
\
#align(center)[$X^(n+k) = X^n * X^k$]
\
#align(center)[$X^(n+k) = (-1) * X^k$]
\
#align(center)[$X^(n+k) = -X^k$]
\
In our case, we have :
\
#align(center)[$b_(n+k)X^(n+k) = -b_(n+k)X^k$]
\
\
Now, consider the polynomial after multiplication:
\
\

#align(center)[$b(X) = sum_(i=0)^(2n-2) b_i X^i$]
\

We split it into two parts : a part that fits in the ring, and a part that is out of it [1]:
\
\

#align(center)[$sum_(k=0)^(n-1) b_k X^k + sum_(k=0)^(n-1) b_(k+n) X^(k+n)$]
\

Using the previous result:
\
\

#align(center)[$b_(k+n)X^(k+n) = -b_(k+n)X^k$]
\
\
We have:
\
\

#align(center)[$sum_(k=0)^(n-1) b_(k+n) X^(k+n) = sum_(k=0)^(n-1) (-b_(k+n)) X^k$]
\
We combine both contributions from [1]:
\
\
#align(center)[$b(X) = sum_(k=0)^(n-1) (b_k - b_(k+n)) X^k$]
\

#align(center)[$c_k = b_k - b_(k+n)$]
\

And in $ZZ_q$ :
\
\

#align(center)[$c_k = (b_k - b_(k+n)) mod q$]
\
#pagebreak()
Now, let's implement it in Rust :
\
\
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    pub fn mul(&self, params: &RingParams, polynomial: &Polynomial) -> Self {
        assert_eq!(self.coeffs.len(), params.n);
        assert_eq!(polynomial.coeffs.len(), params.n);
        
        let mut b = vec![0u64; 2 * params.n];
        
        for i in 0..params.n {
            for j in 0..params.n {
                let k = i + j;
                b[k] += self.coeffs[i]  * polynomial.coeffs[j] ; //[1]

            }
        }
        
        let mut coeffs = vec![0u64; params.n];
        for k in 0..params.n { //[2]
            let low = b[k];
            let high = if k + params.n < b.len() { b[k + params.n] } else { 0 };
            
            let val = ((low as i128) - (high as i128)).rem_euclid(params.q as i128) as u64;
            coeffs[k] = val;
        }

        Polynomial::new(coeffs)
    }
  }
```
First, in [1], we do the naive multiplication, and then, in [2], we apply the formula $c_k = (b_k - b_(k+n)) mod q$ (low is $b_k$ and high is $b_(k+n)$). We use .rem_euclid so that it remains euclidean (and we cannot have negative values).
\
\
It's done ! The polynomial multiplication is implemented. But we'll see later that this implementation, being too slow (complexity $O(n^2)$), will be replaced#footnote[We'll see #link(<poly_mul_ntt>)[the multiplication in ntt domain], but it is recommended to first see the #link(<ntt>)[ntt section] before.].
\
=== Polynomial scaling
\
Scaling a polynomial is simply noted as :
\
#align(center)[$B_k = (A_k * lambda) mod q$]
\
Where $lambda$ is a constant, $q$ is the modulus, $A_k$ is the polynomial we want to scale and $B_k$ is the result of the scaling. It's easily implementable :
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    pub fn scale(&self, params: &RingParams, lambda: u64) -> Self {
        let coeffs: Vec<u64> = self.coeffs
            .iter() //We iterate for each coefficient
            .map(|&coeff| ((coeff as u128 * lambda as u128) % params.q as u128) as u64) //We pass in u128 so that it doesn't overflow, then we scale and reduce by q
            .collect::<Vec<u64>>();
    
        Polynomial::new(coeffs)
    }
  }
```

=== Opposite polynomial
\
Another "operation" is the one that gives the opposite of a polynomial, as :
\
#align(center)[$Â_k = (-A_k) mod q$]
\
In Rust :
\
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    pub fn opposite(&self, params: &RingParams) -> Self { 
        let q = params.q;
        let coeffs: Vec<u64> = self.coeffs
            .iter()
            .map(|&coeff| ( - (coeff as i128 )).rem_euclid(q as i128) as u64) //We convert into i128s, so that it doesn't underflow, then we reduce it. 
            .collect::<Vec<u64>>();
        Polynomial::new(coeffs)
    }
}
```

=== Polynomial reduction
Another operation is the reduction by a constant. It's noted :
\
#align(center)[$Â_k = A_k mod lambda$]
\
Where $lambda$ is a constant.
In Rust, it is written as :
\
#codly(languages: codly-languages)
```rust
#[inline]
pub fn reduce(&self, constant: u128) -> Polynomial { //Function that reduce the polynomial by a constant (polynomial mod k)
    let new = self.coeffs
        .iter()
        .map(|c| (*c as u128).rem_euclid(constant) as u64) //We consider that the constant is an u128. Currently unused since coefficients are u64, but retained for future extensibility.
        .collect();
    Polynomial::new(new)
}
```
#pagebreak()
=== Polynomial division (by a constant)
The last operation we'll implement in this section is the division by a constant. We write it at :
#align(center)[$Â_k = (A_k + lambda/2) slash lambda$]
Why ? Because by default, the compilator does $floor.l x slash y floor.r$ when dividing non-floating numbers, and not a rounding as $floor.l x slash y ceil.r$. For example :

#table(
  columns: 3,
  [*Operation*], [*In Maths with rounding*], [*In Rust*],
  [$x slash y$], [$floor.l x slash y ceil.r$], [$floor.l x slash y floor.r$],
  [$ 7 slash 3$], [$floor.l 2,33... ceil.r = 2$], [$floor.l 2,33... floor.r = 2$],
  [$8 slash 3$], [$floor.l 2,66... ceil.r = 3$], [$floor.l 2,66... floor.r = 2$],
)
When we add $lambda slash 2$, we compensate it. For example :
#table(
  columns: 3,
  [*Operation*], [*In Maths with rounding*], [*In Rust*],
  [$(x + y) slash 2 )slash y$], [$floor.l x slash y ceil.r$], [$floor.l x slash y floor.r$],
  [$ (7 + 1) slash 3$], [$floor.l 2,66... ceil.r = 3$], [$floor.l 2,66... floor.r = 2$],
  [$(8 + 1) slash 3$], [$floor.l 3 ceil.r = 3$], [$floor.l 3 floor.r = 3$],
)

So, in Rust, we implement :
#codly(languages: codly-languages)
```rust
#[inline]
pub fn divide_by_constant( 
    &self,
    constant: u128,
    ) -> Polynomial {

    let new = self.coeffs
        .iter()
        .map(|c| {
            let x = (*c as u128 + constant / 2) / constant; 
            x as u64
        })
        .collect();
     Polynomial::new(new)
}
```
#pagebreak()

== How to use the `Polynomial` code ?

In this section, we'll see how to use the code implemented for polynomials.

Prerequisites :
```bash
cargo add simple-ring
```
Then, in  your project :
```Rust
use simple_ring::{Polynomial, RingParams, find_valid_omega, precalculate};
```

From this, you can use all the methods defined (code from the lib.rs of simple-ring):
#codly(languages: codly-languages)
```rust
fn test_polynomials() {
    let params = RingParams::new(4, 17, find_valid_omega(4, 17)); //We define the parameters
    let ntt_tables = &precalculate(&params);
    let mut coeffs = vec![0u64; 4]; //We create the coefficients for our first polynomial
    coeffs[3] = 8;
    //In all the code, the polynomials should have the same length ! 
    let poly1 = Polynomial::new(coeffs.clone()); //We create the first polynomial as P1 = [0, 0, 0, 8]
    let poly2 = Polynomial::zeros(4); //We create an empty polynomial, which will be the second one.
    let sum = poly1.sum(&params, &poly2); //We execute the defined methods 
    let mul = poly1.mul(&params, &poly2); 
    let mul_ntt = poly1.mul_ntt(&params, ntt_tables, &poly2); 
    let scaled = poly1.scale(&params, 10);
    let divided = poly1.divide_by_constant(2);
    let reduced = poly1.reduce(2);
    let opposite = poly1.opposite(&params);
    println!();
    assert_eq!(poly1.coeffs, coeffs.into_boxed_slice()); //We ensure, with all the assert_eqs, that the result is correct.
    println!("First polynomial : {:?}", poly1);
    println!();
    println!("Second polynomial : {:?}", poly2);
    assert_eq!(poly2.coeffs, vec![0u64; 4].into_boxed_slice());
    println!();
    println!("Sum is : {:?}", sum);
    assert_eq!(poly1.coeffs, sum.coeffs);
    println!();
    println!("Product is : {:?}", mul);
    assert_eq!(poly2.coeffs, mul.coeffs);
    println!();
    println!("Product with NTT is : {:?}", mul_ntt);
    assert_eq!(poly2.coeffs, mul.coeffs);
    println!();
    println!("Scaled first polynomial is : {:?}", scaled);
    let mut coeffs = vec![0u64; 4];
    coeffs[3] = (8 * 10) % params.q; //We have to reduce because the scale is done modulo q
    assert_eq!(coeffs.into_boxed_slice(), scaled.coeffs);
    println!();
    println!("Divided first polynomial is : {:?}", divided);
    let mut coeffs = vec![0u64; 4];
    coeffs[3] = 8 / 2;
    assert_eq!(coeffs.into_boxed_slice(), divided.coeffs);
    println!();
    println!("Reduced first polynomial is : {:?}", reduced);
    let mut coeffs = vec![0u64; 4];
    coeffs[3] = 8 % 2;
    assert_eq!(coeffs.into_boxed_slice(), reduced.coeffs);
    println!();
    println!("Opposite poly1 is : {:?}", opposite);
    let mut coeffs = vec![0u64; 4];
    coeffs[3] = (-8 as i64).rem_euclid(params.q as i64) as u64;//We have to reduce because the opposite is done modulo q
    assert_eq!(coeffs.into_boxed_slice(), opposite.coeffs); 
    println!()
}
```

The output is :
```
running 1 test

First polynomial : Polynomial { coeffs: [0, 0, 0, 8] }

Second polynomial : Polynomial { coeffs: [0, 0, 0, 0] }

Sum is : Polynomial { coeffs: [0, 0, 0, 8] }

Product is : Polynomial { coeffs: [0, 0, 0, 0] }

Product with NTT is : Polynomial { coeffs: [0, 0, 0, 0] }

Scaled first polynomial is : Polynomial { coeffs: [0, 0, 0, 12] }

Divided first polynomial is : Polynomial { coeffs: [0, 0, 0, 4] }

Reduced first polynomial is : Polynomial { coeffs: [0, 0, 0, 0] }

Opposite poly1 is : Polynomial { coeffs: [0, 0, 0, 9] }

test test_polynomials ... ok
```
\
So, the polynomial code is done, we can now approach the sampling !

#pagebreak()
= `sampling.rs` : The coefficient sampling and generation
\
In `sampling.rs`, we implement the generation of coefficients for cryptographic implementations.

== The RNG 
\
A random number generator (RNG) is essential in cryptograpy, because if the generated key & noise aren't random (if they are predictable, if they show patterns), the security of LWE is broken. In this project, we've choosen _OsRng_, a random number generator that calls the system generator (`/dev/getrandom` on Linux, for example.). The OS' RNG called is considered as secured because the generated bits depends on physical values like CPU temperature, disk activity, memory used...
\
So, the first thing to do, in `sampling.rs`, is to define the use of the RNG :
#codly(languages: codly-languages)
```rust
use crate::{Polynomial, RingParams};
use rand::{Rng, RngCore, rngs::OsRng};
```
\
== Implementation for coefficient generation
\
The first thing to do, for implementing the coefficient generation, is to create a struct `Sample`, that will store the coefficients as integers (negative or positive values) :
\
#codly(languages: codly-languages)
```rust
#[derive(Clone, Debug)]
pub struct Sample(pub Vec<i32>);

impl Deref for Sample {
    type Target = Vec<i32>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
```

This struct provides us some modularity : if we want to use values in $ZZ$, we can use the struct `Sample`. At the moment we need to get this values in the ring $ZZ_q$, we just reduce each coefficient modulo $q$. 
\
So, we create a method that implements this transformation :
#codly(languages: codly-languages)
```rust
impl Sample {
    pub fn to_poly(self, q:u64) -> Polynomial {
        let coeffs = self.iter().map(|v| (*v).rem_euclid(q as i32) as u64).collect();
        Polynomial::new(coeffs)
    }
}
```
\
=== Generation of coefficients with Centered Binomial Distribution (CBD)
\
In theory, we should use a gaussian distribution, but it has 2 major problems :

+ The sampling is slow and expensive
+ Its implementation is complicated and source of many errors
\
So, we want to use something simpler, but with similar properties.
Here comes the CBD. We can say that it is a discrete and simple approximation of the gaussian.
We define a CBD variable as :
\
\
#align(center)[$X = sum_(i=1)^eta b_i - b_i prime$]
\
Where $b_i, b_i prime tilde.op {0, 1}$
\
\
Explanation :
\
We do the sum of randomly choosen bits, centered on 0, with a base borned in $[-eta, eta]$.
\
\
Example :
\
Let's say we want to generate a coefficient, called $c$. With centered binomial distribution :
+ We choose the value of $eta$. Here, for the example, $eta$ = 4.
+ We generate randomly $eta$ bits for $b$ and $b prime$. Here, let's say we have $b = [0, 1, 1, 1]$ and $b prime = [0, 1, 0, 0].$
+ We do the sum of this bits, as $b = 0 + 1 + 1 + 1 = 3$ and $b prime = 0 +1+0+0 = 1$.
+ We compute the difference between $b$ and $b prime$ : $b - b prime$ = 3 - 1 = 2
+ We have generated our coefficient : c = 2.

This method has many good points.
\
First, it's really fast : we don't call the generator as much as if we had to implement a gaussian distribution, and the operations are really simple (just a sum and a subtraction, trivial for a CPU).
\
Also, as $eta$ grows, the distribution approaches a Gaussian#footnote[https://en.wikipedia.org/wiki/De_Moivre%E2%80%93Laplace_theorem] and, finally, the CBD is subgaussian.
It's the perfect candidate for LWE cryptography, such as CRYSTAL-Kyber#footnote[https://pq-crystals.org/kyber/] or BFV#footnote[please see `/schemes/`].
\
\
Now, let's implement it :
\
#codly(languages: codly-languages)
```rust
#[inline]
pub fn generate_cbd_sample(n: usize, eta: usize) -> Sample {

    let mut coeffs = vec![0i32; n]; // So first we create an empty vector which will contain the coefficients.

    let bits_per_coeff = eta; //Then we choose the number of bits for each part (a and b) -> if bit_number == 4, a and be will be the sum of 4 bits, like in the example

    let total_bits = 2 * coeffs.len() * bits_per_coeff; 

    let total_bytes = (total_bits + 7) / 8; 

    let mut rng_buf = vec![0u8; total_bytes];

    OsRng.fill_bytes(&mut rng_buf); //We generate a single vector of u8s of which we will choose the bits.
    let mut bit_index = 0;
    for coeff in coeffs.iter_mut() {
        let mut a = 0;
        let mut b = 0;

        for _ in 0..bits_per_coeff { //Then we choose the bits in the sequence of bytes generated before. (for example : generated = [00001111; 10101010; ...], then we pick the bits one by one as first bit = 0, second one = 0...)
            let byte = rng_buf[bit_index / 8];
            let bit = (byte >> (bit_index % 8)) & 1; 
            a += bit as u64;
            bit_index += 1;
        }

        for _ in 0..bits_per_coeff { //We continue picking
            let byte = rng_buf[bit_index / 8];
            let bit = (byte >> (bit_index % 8)) & 1;
            b += bit as u64;
            bit_index += 1;
        }

        *coeff = a as i32 - b as i32; //And we finally do a - b
    }
    
    Sample(coeffs) //We return the generated sample
}
```
\
=== Generation of small coefficients
\
We will also need to generate small coefficients for our schemes. The generated coefficients will be in the set ${-1, 0, 1}$.
\
We simply implement it :
\
```rust
#[inline]
pub fn generate_small_sample(params: &RingParams) -> Sample { 
    let mut rng = OsRng; 
    let mut coeffs: Vec<i32> = Vec::with_capacity(params.n);
    
    for _ in 0..params.n {
        let small: i32 = rng.gen_range(-1..=1); //We generate coeffs in the set A = {-1, 0, 1}
        coeffs.push(small);
    }
    
    Sample(coeffs) //We return the generated sample
}
```
\
=== Uniform generation of coefficients in the Ring
\
Finally, we need to have a function for generating coefficients uniformly, in the entire ring, so in the set ${0, 1, ..., q - 1}$.
\
```rust
#[inline]
pub fn generate_uniform_polynomial(params: &RingParams) -> Polynomial { 
    let mut rng = OsRng; //We choose the rng
    let mut coeffs = Vec::with_capacity(params.n);

    for _ in 0..params.n {
        let uniform: u64 = rng.gen_range(0..=params.q - 1); // We generate values that are in the ring 
        coeffs.push(uniform);
    }
    Polynomial { coeffs: coeffs.into_boxed_slice() } //This time, we return directly a Polynomial, because we are in the ring.
}
```
\
We have now finished with the sampling. Now, we will approach the most difficult concept of this implementation : the NTT.

#pagebreak()
= Delving into NTT <ntt> 
\
The Number Theoretic Transform is the equivalent of the FFT, but in modular arithmetic : while the FFT is computed on complex numbers and roots of unity as $omega^n = 1$, the NTT works on a finite field (the ring), with integers modulo $q$ and a primitive root modulo $q$.

== The problem
\
Let $A(X)$ and $B(X)$ be two polynomials :
\
#align(center)[$A(X) = a_0 + a_1 hyph.point X^1 + a_2 hyph.point X^2$]
#align(center)[$B(X) = b_0 + b_1 hyph.point X^1 + b_2 hyph.point X^2$]
\
Multiplying two polynomials has a complexity of $O(n^2)$, which is enormous for large polynomials. So, we are searching for a representation which reduces the complexity of the operation.

== The concept
\
The NTT says that we can't only represent a polynomial by their coefficients :
#align(center)[($a_0, a_1, a_2$)]
#align(center)[($b_0, b_1, b_2$)]
\
But also by the values of the polynomial in some points :
#align(center)[$(A(omega^0), A(omega^1), A(omega^2))$]
#align(center)[$(B(omega^0), B(omega^1), B(omega^2))$]
\
Where $omega$ is a root of unity.
\
In this representation, we just have to multiply coefficient by coefficient to get the result of the polynomial multiplication.

#pagebreak()
== The maths behind NTT
=== What is the root of unity ?
\
In standart arithmetic, a root of unity is a number $omega$ as, for the unity $n$ :
#align(center)[$omega^n = 1$]
\
For example, for $n = 4$, $omega = i$ because $i^4 = 1$.
\
\
But, in the modular arithmetic (in $ZZ_q$), the root is a number $omega$ as, for the unit $n$ :
#align(center)[$omega^n eq.triple 1 mod q$]
\
For example, for $q = 17$ and $n = 4$, $w = 4$ because $4^4 mod 17 = 256 mod 17 = 1$.
\
\
=== What's a primitive root, and why is it important ?
\
A primitive root is a root that "generate" all the other ones.
A number $omega$ is a primitive root if :
#align(center)[$omega^n eq.triple 1 mod q$]
#align(center)[$omega^k eq.triple.not 1 mod q$]
Where $k < n$.
\
For example, for  $q = 17$ and $n = 4$, $w = 4$ is a primitive root because :
#align(center)[$4^1 mod 17 = 4 mod 17 eq.triple 4 eq.triple.not 1$]
#align(center)[$4^2 mod 17 = 16 mod 17 eq.triple 16 eq.triple.not 1$]
#align(center)[$4^3 mod 17 = 64 mod 17 eq.triple 13 eq.triple.not 1$]
#align(center)[$4^4 mod 17 = 256 mod 17 eq.triple 1$]
\
Why do we need a primitive root ? 
\
Because we need $omega^0 eq.not omega^1 eq.not omega^2 eq.not  ... eq.not omega^(n-1)$.
\
Or, if $omega$ isn't a primitive root, some of the values can repeet, and so we loose information.

=== The negacyclic
\
In BFV, we work in the ring $ZZ_q [X] slash (X^n + 1)$, which means that $X^n eq.triple -1 mod (X^n + 1)$
. So, we need $omega^n eq.triple -1 mod q$.
\
The solution is to take a 2nth root of unity, as :
\
#align(center)[$omega^(2n) eq.triple 1 mod q => omega^n eq.triple -1 mod q$]
\
Because $omega^(2n) = (omega^n)^2 eq.triple 1$, so $omega^n$ is a square root of $1$, and, in the ring, the square roots of $1$ are ${-1, 1}$. If $omega$ is a primitive 2nth root, $omega^n eq.not 1$, so $omega^n eq -1$.
\
\
Now, we introduce the fact that $q eq.triple 1 mod 2n$. Why ? Because a primitive root 2nth of unity exists in $ZZ_q$ if and *only* if $2n$ divides $(q-1)$.
\
\
For example, if we have $n = 4096$ and $q = 557 057$, it works, because :
\
#align(center)[$q - 1 mod 2n = 557 056 mod 8192 eq 0$]
\
In that case, a valid $omega$ exists.

\
== The NTT Transform
=== The formal definition of the forward NTT

This is the formal definition of the NTT :
\
Let $a(x)$ be a polynomial of coefficients $[a_0, a_1, ..., a_(n-1)]$.
\
The NTT computes :
#align(center)[$â_i = sum_(j=0)^(n-1) a_j hyph.point omega^(i hyph.point j) mod q$]
\
And then returns $[â_0, â_1,..., â_(n-1)]$.
\
\For example, with $n = 4, q = 17, omega = 4$, and $a =  [1, 2, 3, 0]$, we have :
\
\
#align(center)[$â_0 = (a_0 hyph.point omega^0 + a_1 hyph.point omega^0 + a_2 hyph.point omega^0 + a_3 hyph.point omega^0 ) mod 17$]
#align(center)[$â_0 = (1 hyph.point 1 + 2 hyph.point 1 + 3 hyph.point 1 + 0 hyph.point 1) mod 17$]
#align(center)[$â_0 = 6$]
\
\
#align(center)[$â_1 = (a_0 hyph.point omega^0 + a_1 hyph.point omega^1 + a_2 hyph.point omega^2 + a_3 hyph.point omega^3 ) mod 17$]
#align(center)[$â_1 = 57 mod 17 = 6$]
\
\
#align(center)[$â_2 = (a_0 hyph.point omega^0 + a_1 hyph.point omega^2 + a_2 hyph.point omega^4 + a_3 hyph.point omega^6 ) mod 17$]
#align(center)[$â_2 = 36 mod 17 = 2$]
\
\
#align(center)[$â_3 = (a_0 hyph.point omega^0 + a_1 hyph.point omega^3 + a_2 hyph.point omega^6 + a_3 hyph.point omega^9 ) mod 17$]
#align(center)[$â_3 = 75 mod 17 = 7$]
\
\
The result is here $â = [6, 6, 2, 7]$, we've transform our polynomial into the NTT domain !
\
But, there is a problem : the computation cost. As you've seen, we have done, for every $a$, 4 sums and 4 products. So, the complexity is $O(2n^2)$.
\
\
=== The formal definition of the inverse NTT
\
We've seen the formal definition of the forward NTT. But, to get back into the "normal" coefficients domain, we need an operation called the inverse NTT.
\
It's formal definition is :
\
\
#align(center)[$a_j = n^(-1) hyph.point sum_(i=0)^(n-1) â_i hyph.point omega^(-i hyph.point j) mod q$]
\
So, basically, the difference is in the $-i$ (we compute the inverse of $omega^(i hyph.point j)$) and the factor $n^(-1)$.
\
\
For example, with the computed coefficients $â = [6, 6, 2, 7]$, we have :
\
\
#align(center)[$a_0 = n^(-1) hyph.point (â_0 hyph.point omega^0 + â_1 hyph.point omega^0 + â_2 hyph.point omega^0 + â_3 hyph.point omega^0 ) mod 17$]
#align(center)[$a_0 = n^(-1) hyph.point (6 hyph.point 1 + 6 hyph.point 1 + 2 hyph.point 1 + 7 hyph.point 1) mod 17$]
#align(center)[$a_0 = 1/4 hyph.point 21 mod 17$]
#align(center)[$a_0 = 1$]

\
\
#align(center)[$a_1 = n^(-1) hyph.point (â_0 hyph.point omega^0 + â_1 hyph.point omega^(-1) + â_2 hyph.point omega^(-2) + â_3 hyph.point omega^(-3) ) mod 17$]
#align(center)[$a_1 = 2$]
\
\
#align(center)[$a_2 = n^(-1) hyph.point (â_0 hyph.point omega^0 + â_1 hyph.point omega^(-2) + â_2 hyph.point omega^(-4) + â_3 hyph.point omega^(-6) ) mod 17$]
#align(center)[$a_2 = 3$]
\
\
#align(center)[$a_3 = n^(-1) hyph.point (â_0 hyph.point omega^0 + â_1 hyph.point omega^(-3) + â_2 hyph.point omega^(-6) + â_3 hyph.point omega^(-9) ) mod 17$]
#align(center)[$a_3 = 0$]
\
Done ! We have our original coefficients : $a = [1, 2, 3, 0]$.
\
\
=== Proof that INTT(NTT(a)) = a
\
Now, we want to prove that INTT(NTT(a)) = a in the negacyclic case.
\
We work with $omega in ZZ_q$, a primitive *2n-th* root of unity (as seen before):
\
\
#align(center)[$omega^(2n) equiv 1 (mod q) quad $and$ quad omega^n equiv -1 (mod q)$]
\
#strong[Step 1: Definitions]
\
\
NTT:
\
#align(center)[$hat(a)_k = sum_(j=0)^(n-1) a_j hyph.point omega^(k hyph.point j) mod q$]
\
INTT :
\
\
#align(center)[$r_i = n^(-1) hyph.point sum_(k=0)^(n-1) hat(a)_k hyph.point omega^(-i hyph.point k) mod q$]
\
#strong[Step 2: Substitution]
\
Substitute $hat(a)_k$ into the INTT formula:
\
\
#align(center)[$r_i = n^(-1) hyph.point sum_(k=0)^(n-1) (sum_(j=0)^(n-1) a_j hyph.point omega^(k hyph.point j)) hyph.point omega^(-i hyph.point k) mod q$]
\
#align(center)[$r_i = n^(-1) hyph.point sum_(k=0)^(n-1) hyph.point sum_(j=0)^(n-1) a_j hyph.point omega^(k hyph.point j) hyph.point omega^(-i hyph.point k) mod q$]
\
#align(center)[$r_i = n^(-1) hyph.point sum_(k=0)^(n-1) hyph.point sum_(j=0)^(n-1) a_j hyph.point omega^(k hyph.point (j - i)) mod q$]
\
#strong[Step 3: Orthogonality Lemma]
\
Let $m = j - i$. We analyze the inner sum:
\
\
#align(center)[$S(m) = sum_(k=0)^(n-1) omega^(k hyph.point m)$]
\
#table(
  columns: 2,
  [*Case*], [*Value of S(m)*],
  [$j = i$ (so $m = 0$)], [$omega^0 = 1$, so $S(0) = sum_(k=0)^(n-1) 1 = n$],
  [$j eq.not i$ (so $m eq.not 0$)], [Geometric serie, see below],
)
\
If $j eq.not i$, we have a geometric serie :
#align(center)[$S(m) = 1 + omega^m + omega^(2m) + ... + omega^((n-1)m)$]
#align(center)[$S(m) = (1 - omega^(n hyph.point m)) / (1 - omega^m)$]

Now, since $omega^(2n) equiv 1 (mod q)$:
\
\
#align(center)[$omega^(n hyph.point m) = (omega^n)^m equiv (-1)^m (mod q)$]
\
\
For $m$ even: $omega^(n m) equiv 1$, so numerator $= 1 - 1 = 0$.
  
For $m$ odd: $omega^(n m) equiv -1$, but the sum still equals 0 
(alternating series $1 - 1 + 1 - 1 + ... = 0$ for even $n$).
In both cases: $S(m) = 0$ when $j eq.not i$. 

#strong[Step 4: Apply Orthogonality]

Only the term where $j = i$ contributes:
#align(center)[$r_i = n^(-1) hyph.point (a_0 hyph.point 0 + a_1 hyph.point 0 + ... + a_i hyph.point n + ... + a_(n-1) hyph.point 0) mod q$]

#align(center)[$r_i = n^(-1) hyph.point a_i hyph.point n mod q$]

#align(center)[$r_i = a_i mod q$]
\
#strong[Conclusion:] We have recovered our coefficient ! 
\
\
=== Proof that INTT(NTT(a) $*$ NTT(b)) = a $*$ b
\
What we want is to multiply the polynomials in the NTT domain, coefficient by coefficient.
\
We've said before that the formula of the polynomial multiplication was :
\
\
#align(center)[$c_k = sum_(i=0)^(n-1) sum_(j=0)^(n-1) a_i b_j $ where $ i+j equiv k (mod 2n)$]
\
With the constraint $X^n = -1$ :
\
#align(center)[$r_k = c_k - c_(k+n) mod q$]
\
Where $r$ is the final result of the multiplication.
\
For explanations and more details, please see the polynomial mul section#footnote[ #link(<poly_mul>)[poly mul section]].
\
\
We've also seen the formula of the forward NTT and the inverse NTT. So, let the proof begin :
\
\
Let :
\
- $â = $ NTT($a$), $hat(b) =$ NTT($b$)
- $hat(c) = â dot.o hat(b) $
\
We want to prove that INTT($hat(c)) = a hyph.point b$
\
\
Let $r = $ INTT($ĉ$). We have :
\
\
#align(center)[$r_m = n^(-1) hyph.point sum_(k=0)^(n-1) ĉ_k hyph.point omega^(-m hyph.point  k)$]
\
But $ĉ_k = â_k dot.o hat(b)$, so :
\
#align(center)[$r_m = n^(-1) hyph.point sum_(k=0)^(n-1) (â_k hyph.point hat(b)_k) hyph.point omega^(-m hyph.point k)$]
\
We substitute $â$ and $hat(b)$ by their NTT definitions :
\
\
#align(center)[$r_m = n^(-1) hyph.point sum_(k=0)^(n-1) hyph.point (sum_(i=0)^(n-1) a_i hyph.point omega^(k hyph.point i)) hyph.point (sum_(j=0)^(n-1) b_j hyph.point omega^(k hyph.point j)) hyph.point omega^(-m hyph.point k)$]
\
We can now rearrange the sums :
\
\
#align(center)[$r_m = n^(-1) hyph.point sum_(k=0)^(n-1) hyph.point sum_(i=0)^(n-1) hyph.point sum_(j=0)^(n-1) hyph.point a_i hyph.point b_j hyph.point omega^(k hyph.point i) hyph.point omega^(k hyph.point j) hyph.point omega^(-m hyph.point k)$]
\
#align(center)[$r_m = n^(-1) hyph.point sum_(i=0)^(n-1) hyph.point sum_(j=0)^(n-1) hyph.point a_i hyph.point b_j hyph.point sum_(k=0)^(n-1) hyph.point omega^(k (i + j - m))$]
\
We have, as seen before :
#table(
  columns: 2,
  [*Possibility*], [*Value of the sum*],
  [$i + j - m equiv 0 (mod n)$], [$S = n$],
  [$i + j - m equiv.not 0 (mod n)$], [$S = 0$],
)
\
So the only term where $i + j equiv m (mod n)$ contributes. In conclusion, we have :
\
#align(center)[$r_m = n^(-1) hyph.point sum_(i=0)^(n-1) hyph.point sum_(j=0)^(n-1) hyph.point a_i hyph.point b_j times n times delta_(i+j equiv m)$]
\
#align(center)[$r_m = sum_(i=0)^(n-1) sum_(j=0)^(n-1) a_i b_j $ where $ i+j equiv m (mod n)$]
\
And then because $omega^n = -1$, all terms of degree $>= n$ are automatically reduced. So, the computation of the INTT rebuild exactly the coefficients $r_k$ of $a_k * b_k$ in $ZZ_q$ :
\
\
#align(center)[$r_k = sum_(i+j ≡ k (mod n)) ^ (n-1) a_i hyph.point b_j  $  knowing that $omega^n = -1$]
\
#align(center)[$= sum_(i+j = k) ^  (n-1) a_i hyph.point b_j  -  sum_(i+j = k+n) a_i hyph.point b_j  mod q$]
\
#align(center)[$= c_k$]
\
=== The trick to reduce complexity : the butterfly operation 
\
As we've seen, the formal definition of the NTT is :
\
#align(center)[$â_i = sum_(j=0)^(n-1) a_j hyph.point omega^(i hyph.point j) mod q$]
\
The key is to split even and odd indices. For $n= 4$, let's expand the sum and group the terms :
\
#align(center)[$â_i = a_0 * omega^0 + a_1 * omega^i + a_2 * omega^(2i) + a_3 * omega^(3i)$]
\
We group the indices $(0,2)$ and $(1, 3)$ :
\
#align(center)[$â_i = (a_0 * omega^0 + a_2 * omega^(2i)) + (a_1 * omega^(i) + a_3 * omega^(3i))$]
\
We factor out $omega^i$ from the odd part (right) :
\
#align(center)[$â_i = (a_0 * omega^0 + a_2 * omega^(2i)) + omega^i (a_1 * omega^(0) + a_3 * omega^(2i))$]
\
We now define :
\
\
 #align(center)[Evenpart(i) = $a_0*omega^0 + a_2 * omega^(2i)$]
\
#align(center)[Oddpart(i) = $a_1*omega^0 + a_3 * omega^(2i)$]
\
Therefore :
#align(center)[$â_i = $ Evenpart(i) + $omega^i *$ Oddpart(i)]
\
\
Then, knowing that $omega^(i+n slash 2) = -omega^i$, we have :
\
#align(center)[$â_i = $ Evenpart(i) + $omega^i *$ Oddpart(i)]
#align(center)[$â_(i+n slash 2) = $ Evenpart(i) - $omega^i *$ Oddpart(i)]
\
And so, for two coefficients, we only have to compute the same Evenpart, the same Oddpart. We reduce the complexity by two. By computing $omega^i * $ Oddpart(i) only one time for the two coefficients, we reduce it again, and, by accessing only one index of coefficients $(i)$ for the results of index $i$ and $i + n slash 2$, we reduce the memory cost !
\
Why $O( n log n)$ ? Because the butterfly is applied $log_2(n)$ times : 
#table(
    columns: 4,
    [Level], [Butterflies], [Work per Butterfly], [Total Cost],
    [1], [n/2], [O(1)], [O(n)],
    [2], [n/2], [O(1)], [O(n)],
    [...], [...], [...], [...],
    [$log_2(n)$], [n/2], [O(1)], [O(n)],
)

In total, we have a cost of $log_2(n) * O(n) = O(n log n)$. For exampe, with $n = 4096$, naively we do $4096² = 16,777,216$ operations, and with the butterflies we do $n slash 2 * log_2(n) = 2048 * 12 = 24,586$ operations, so a gain factor of $tilde 682$. 
\
Now, before implementing the NTT code, we will have to implement modular arithmetic functions for searching parameters.

#pagebreak()
== `modular.rs` : modular arithmetic functions and useful ones for searching parameters.
\
=== Finding the parameters
\
The first thing to do, for the NTT, is to choose the parameters, as $q mod 2n = 1$ and $omega$ is a primitive 2nth root of $n$. First, let's implement an algorithm for modular exponentiation.
\
The concept of the modular exponentiation is that the result of $k^n mod q$ is in our ring, in $[0; q-1]$, so that it doesn't overflow. The problem is that if $k$ and $n$ are enormous, $k^n$ would overflow. The trick is here to avoid computing $k^n$ directly, and to compute $k^n mod q$ step by step.
\
Here, instead of doing $k * k *k *... * k$ $n$ times, we use the binary decomposition of the exponent $n$.
\
==== Binary decomposition of the exponent
\
In binary, the exponent $n$ is written as $n = sum_(j=0)^l b_j hyph.point 2^j$
\
Where $b_j in {0, 1}$. 
\
\
For example $n = 13$ is written as 1101 in binary because :
#align(center)[$1 *2^0 + 0*2^1 + 1*2^2 + 1*2^3 = 1 + 0 + 4 + 8 = 13$] 
\
Why 1101 and not 1011 ? Because in binary we write from the most significant bit to the less significant. Since $1*2^0$ is the less significant and $1 * 2^3$ is the most significant, we write it from $1*2^3$ to $1*2^0$, so 1101.

==== Property of the powers, and computation
We have this property :
#align(center)[$k^n = k^(sum_(j=0)^l b_j hyph.point 2^j)$]
#align(center)[$k^n = product_(j=0)^l k^(b_j hyph.point 2^j)$]
#align(center)[$k^n = product_(j=0)^l (k^(2^j))^(b_j)$]
\
The fact is that if $b_j = 0$, $(k^(2^j))^(b hyph.point j) = 1$, so we can ignore this term, and, if $b_j = 1$, we multiply by $k^(2^j)$.
\
\
So, we can calculate $k^(2l)$ in an iterative way :
#align(center)[$k^(2^0) = k$]
#align(center)[$k^(2^1) = (k^(2^0))^2 = k^2$]
#align(center)[$k^(2^2) = (k^(2^1))^2 = k^4$]
#align(center)[$k^(2^3) = (k^(2^2))^2 =  k^8$]
#align(center)[$...$]
\
Every step, we do : $k = (k * k) mod q$.
\
==== The modular exponentiation algorithm
\
Because of that property, we can implement a step by step function for mudlar exponentiation in Rust :
\
```rust
pub fn mod_pow(mut base: u128, mut exp: u128, modulus: u128) -> u128 {
    let mut result = 1u128;
    base %= modulus; //First, we reduce the base with the modulo.
    while exp > 0 { //Then, while the exponent is not equal to 0, we continue the exponentiation
        if exp & 1 == 1 { //If the less significant bit is 1, we multiply
            result = (result * base) % modulus;
        }
        base = (base * base) % modulus; //We prepare the base for the next iteration
        exp >>= 1; //We pass to the next bit. (so that the next bit becomes the less significant bit for next step)
    }
    result //We return the result of the exponentiation
}
```
This method avoids the overflow, and is fast, because we have at most $log₂(exp)$ iterations. 
Since exp is a the most of the time an u64 in our code, $log₂(2^64) = 64$ iterations maximum.

==== Finding $q$
\
We'll not implement a function for searching $q$, because it depends on the scheme we choose. For example, $q$ in BFV is totally different from $q$ in CKKS (in BFV, we'll not implement the RNS#footnote[https://en.wikipedia.org/wiki/Residue_number_system], but in CKKS we'll not have the choice). 
\
But, we can already implement an algorithm that returns a boolean, and that check if $q$ is compatible with the NTT or not.
First, let's implement an algorithm that tests if a number is prime or not. 

===== The `is_prime` algorithm
\
#codly(languages: codly-languages)
```rust
fn is_prime(n: u64) -> bool {
    if n < 2 { return false; }      // 0, 1 aren't primes
    if n == 2 { return true; }       // 2 is prime, and the only even prime 
    if n.is_multiple_of(2) { return false; }  // All other even numbers aren't prime
    
    // Test divisors from 3 to √n
    let mut i = 3u64;
    while i * i <= n {              // Condition : i ≤ √n
        if n.is_multiple_of(i) {    // if i divide n
            return false;           // n isn't a prime number
        }
        i += 2;                     // Next one
    }
    true  // If no divisor was found, n is prime
}
```
\
Why do we test to $sqrt(n)$ ? Because if n as a divisor $d > sqrt(n)$, $n/d < sqrt(n)$ is also a divisor.
\
Proof :
\
Let $d$ be a divisor of $n$ as $d > sqrt(n)$. We have $n = d * k$.
\
If $k > sqrt(n)$, $d * k > sqrt(n) * sqrt(n) = n$. But it isn't possible, since $d$ is a divisor of $n$.
\
So $k lt.eq n$, and so we just have to test the divisors from 3 to $sqrt(n)$.

===== The `is_q_valid` algorithm
\
Now, we can implement the algorithm :
\
```rust
pub fn is_q_valid(n: usize, q: u64) -> bool {
    if n == 0 || q < 2 {  //If q < 2, or n = 0, then it can not be valid
        return false;
    }
    
    if !is_prime(q) { //if it is not prime, it cannot be valid
        return false;
    }
    
    let two_n = 2 * n as u64; //If the condition q - 1 mod 2n == 0 is true, then q is valid
    (q - 1) % two_n == 0
}
```

==== Finding $omega$
\
Now that we have $q$, `is_prime`, and $n$, we can find $omega$ as a primitive 2nth root of $n$ :
\
```rust
pub fn find_valid_omega(n: usize, q: u64) -> u64 { 
    let two_n = 2 * n;
    let exp = (q - 1) / two_n as u64;
    
    for candidate in 2..q {
        let omega = mod_pow(candidate as u128, exp as u128, q as u128) as u64;
        
        let omega_n = mod_pow(omega as u128, n as u128 , q as u128);
        if omega_n == (q as u128 - 1)  {
            return omega;
        }
    }
    panic!("No valid omega found");
}
```
\
Why does $e = (q -1) slash 2n $ ? :
\
\
The function needs to return an integer so that $omega$ is a primitive 2nth root of unity in $ZZ_q$:
+ $omega^(2n) equiv 1 (mod q)$
+ $omega^n equiv -1 (mod q)$
+ $omega^k equiv.not 1 (mod q)$ for each $k < 2n$ 
\
We know that $q equiv 1 (mod 2n)$, so $e = (q-1) slash (2n)$ is an integer.
\
For each candidate $c in [2, q-1]$ :
#align(center)[$omega = c^e mod q$]
\
Because of Fermat's little theorem#footnote[https://en.wikipedia.org/wiki/Fermat%27s_little_theorem], we have :
#align(center)[$c^(q-1) equiv 1 (mod q)$]
\
So :
#align(center)[$omega^(2n) = (c^e)^(2n)$]
#align(center)[$omega^(2n) = c^(e * 2n)$]
#align(center)[$omega^(2n) = c^(q-1)$]
#align(center)[$omega^(2n) equiv 1 (mod q)$]
\
It works !
\
#pagebreak()

== `ntt.rs` : implementing the NTT, in Rust
\
Now, we can - finally - implement the NTT in Rust. First, we'll detail the _twiddle precalculation_.

=== Twiddle precalculation
\
A _twiddle_ is a precomputed power of $omega$, as :
\
\
#align(center)[$t_k = omega^k mod q$]
\
It's called twiddles because in FFT and NTT, the values are "twiddled" (I think it's the reason, but maybe I'm wrong).
\
\
We have :
\
#align(center)[$r(x)$ = bit_reverse(x)]
\
#align(center)[$t[k] = omega^(r(k)) mod q$]
\
#align(center)[$overline(t)[k] = omega^(-r(k)) mod q$]
\
#align(center)[$psi = omega$]
\
#align(center)[$overline(psi) = omega^(-1) mod q$]
\
\
Where not overlined means for forward NTT, and overlined means for inverse NTT.
\
We have a bit-reversed order because the "Merge in place" algorithm access to the twiddles in an order that correspond to bit_reversal of indices (We'll see it later). Instead of calculating bit_reverse(k) every time, we precompute it in bit-reversed order, so that the bit_reverse is done one time, and not $O(n log(n))$ times.

So, to precompute the twiddles, we first create a structure called  :
\
```rust
use crate::RingParams;
use crate::modular::mod_pow;
use crate::polys::Polynomial;

#[derive(Clone)]
pub struct NTTprecaculated {
    twiddles: Box<[u128]>, //Storage for twiddles
    twiddles_inv: Box<[u128]>, //Storage for inv_twiddles
}
```
\
Then, we implement the precalculation of the twiddles :
\
```rust
pub fn precalculate(params: &RingParams) -> NTTprecaculated {
    let n = params.n;
    let q = params.q as u128;
    let psi = params.omega as u128;  //Yes, it's just a name changing, but it's how it's written in the formula.
    let log_n = n.trailing_zeros(); //Because n is a power of 2, the number of trailing zeros gives us log_2(n)
   
    let mut twiddles = vec![1u128; n];
    for k in 0..n {
        let br_k = k.reverse_bits() >> (64 - log_n); //Reverse bit of k on log_n bits
        let power = br_k as u128;        
        twiddles[k] = mod_pow(psi, power, q); //The twiddle is psi^bit_reversed(k)
    }
    
  
    let psi_inv = mod_pow(psi, q - 2, q); //because of fermat's little theorem
    let mut twiddles_inv = vec![1u128; n];
    for k in 0..n {
        let br_k = k.reverse_bits() >> (64 - log_n);
        let power = br_k as u128;
        twiddles_inv[k] = mod_pow(psi_inv, power, q); 
    }
    
    NTTprecaculated {
        twiddles: twiddles.into_boxed_slice(), //We return the twiddles
        twiddles_inv: twiddles_inv.into_boxed_slice(), //And the twiddle inv
    }
}
```
What are trailing zeros ? Trailing zeros are non-significants zeros in binary representation. For example, with $n = 4096$, we have :
#align(center)[$n = 4096$]
#align(center)[$n = 2^12$]
#align(center)[$n = 1000000000000$]
There are 12 trailing zeros, and $log_2(4096) = 12$.
\
\
Why using $log_2(n)$ ? Because we do the bit_reverse on exactly $log_2(n)$ bits. For example, with $n = 8 :$
#align(center)[$n = 2^3$]
#align(center)[$log_2(2^3) = 3$]
#align(center)[$k = 1 = 001 => r(k) = 100 = 4$]
#align(center)[$k = 2 = 010 => r(k) = 010 = 2$]
#align(center)[$k = 3 = 011 => r(k) = 110 = 6$]
\
#pagebreak()
=== Forward NTT in single thread
\
The NTT used here is a modern one from this paper : #link("https://eprint.iacr.org/2022/1222.pdf")[Homomorphic encryption on GPU, 2022/1222]#footnote[Özcan, Ali & Ayduman, Can & Türkoğlu, Enes & Savaş, Erkay. (2023). Homomorphic Encryption on GPU. IEEE Access. PP. 1-1. 10.1109/ACCESS.2023.3265583.].  
```rust
fn forward_ntt_single(
    params: &RingParams, //We'll use the defined parameters,
    polynomial: &Polynomial, //The polynomial to convert in NTT domain,
    ntt_tables: &NTTprecaculated //And the precalculated twiddles.
) -> Polynomial {
    let mut coeffs: Vec<u64> = polynomial.coeffs.to_vec();
        
    let n = params.n;
    let q = params.q as u128; //Conversion for later
    let mut t: usize = n; 
    let mut m: usize = 1;

    loop { 
        t /= 2; //Distance between 2 butterflies 
        for i in 0..m {  //For every group of butterflies
            let j1 = 2 * i * t; 
            let j2 = j1 + t - 1;

            for j in j1..=j2 {
                let u = coeffs[j] as u128; //The butterfly operation
                let w = ntt_tables.twiddles[m + i]; //We use the precomputed twiddles
                let v = ((coeffs[j + t]) as u128 * w) % q; //Reduction so that it remains in the ring
                    
                    let mut x = u + v; //High (a_i)
                    if x >= q { x -= q; } //reduction
                    coeffs[j] = x as u64; //We insert the coefficient

                    let y = if u >= v { u - v } else { u + q - v }; //Low (a_(i+t)) then reduction
                    coeffs[j + t] = y as u64; //We instert the coefficient

            }
        }

        m *= 2; 

        if m >= n { break; } //To stop the loop, when it's finished
    }

    Polynomial {
        coeffs: coeffs.into_iter().collect::<Vec<_>>().into_boxed_slice(), //We return the coefficients, into a Polynomial.
    }
}
```
Explanation :
\
\
The $t$ iteration is done so that we get the coefficients that are in pair :
\
  t=4:  [0]◄──4──►[4]  [1]◄──4──►[5]  [2]◄──4──►[6]  [3]◄──4──►[7]
  \
  \
  t=2:  [0]◄─2─►[2]  [1]◄─2─►[3]  [4]◄─2─►[6]  [5]◄─2─►[7]
  \
  \
  t=1:  [0]◄1►[1]  [2]◄1►[3]  [4]◄1►[5]  [6]◄1►[7] 

\
The $m$ iteration is done so that all butterflies that uses the same twiddle factor uses the twiddle factor of index $m$. We do $m = m*2$ because each time we divide the distance between two butterflies ($t$), we scale by 2 the number of groups.
\
\
$j_1$ and $j_2$ are the bounds of the group :
#align(center)[$j_1 = 2 * i *t$ -> index of the first bound]
#align(center)[$j_2 = j_1 + t -1$ -> index of the second bound]
\
\
And $j$ is the index of $u$ in each butterfly.
\
\
For example, with $n = 8$, at the second iteration ($t = 2, m = 2$) :
\
\
Group $i = 0$ :
\
#align(center)[$j_1 = 2 * 0 * 2 = 0$]
#align(center)[$j_2 = 0 + 2 - 1 = 1$]
\
#align(center)[Butterflies on coeffs[j]↔coeffs[j + t] and coeffs[j]↔coeffs[j + t].]
#align(center)[Butterflies on coeffs[0]↔coeffs[2] and coeffs[1]↔coeffs[3].]
\
Group $i = 1$ :
#align(center)[$j_1 = 2 * 1 * 2 = 4$]
#align(center)[$j_2 = 4 + 2 - 1 = 5$]
\
#align(center)[Butterflies on coeffs[j]↔coeffs[j + t] and coeffs[j]↔coeffs[j + t].]

#align(center)[Butterflies on coeffs[4]↔coeffs[6] and coeffs[5]↔coeffs[7].]
#align(center)[ . . .]
\
\
We can visualize like this, for example :
\
\
Initial state : coeffs = $[a_0, a_1, a_2, a_3, a_4, a_5, a_6, a_7]$.
\
\
\
Iteration 1 : $t=4$, $m=1$ :
\                       
\           
Group $i=0$ : $j_1=0$,  $j_2=3$                                
#align(center)[j=0 : coeffs[0] ↔ coeffs[4]  (twiddle = twiddles[1])]
#align(center)[j=1 : coeffs[1] ↔ coeffs[5]  (twiddle = twiddles[1])]
#align(center)[j=2 : coeffs[2] ↔ coeffs[6]  (twiddle = twiddles[1])]
#align(center)[j=3 : coeffs[3] ↔ coeffs[7]  (twiddle = twiddles[1])]
\                                     
4 butterflies, same twiddle, distance of 4.                
\
\
\
Iteration 2 : $t=2$, $m=2$ : 
\
\                                 
Group $i=0$ : $j_1=0$ , $j_2=1$ :                                
#align(center)[j=0 : coeffs[0] ↔ coeffs[2]  (twiddle = twiddles[2])]
#align(center)[j=1 : coeffs[1] ↔ coeffs[3]  (twiddle = twiddles[2])]
\
\                                                    
Group $i=1$ : $j_1=4$, $j_2=5$                                
#align(center)[j=4 : coeffs[4] ↔ coeffs[6]  (twiddle = twiddles[3])]
#align(center)[j=5 : coeffs[5] ↔ coeffs[7]  (twiddle = twiddles[3])]
\
2 groups of 2 butterflies, distance of 2            
\
\
\

Iteration 3 : $t=1$, $m=4$                                  
#align(center)[Group $i=0$ : $j_1=0, j_2=0$ → $j=0$ : coeffs[0] ↔ coeffs[1] (twiddles[4])]
#align(center)[Group $i=1$ : $j_1=2, j_2=2$ → $j=2$ : coeffs[2] ↔ coeffs[3] (twiddles[5])]
#align(center)[Group $i=2$ : $j_1=4, j_2=4$ → $j=4$ : coeffs[4] ↔ coeffs[5] (twiddles[6])]
#align(center)[Group $i=3$ : $j_1=6, j_2=6$ → $j=6$ : coeffs[6] ↔ coeffs[7] (twiddles[7])]
\
4 groups of 1 butterfly, distance of 1                  

Result : coeffs = $[â_0, â_4, â_2, â_6, â_1, â_5, â_3, â_7]$ (order bit-reversed)

#pagebreak()
=== Forward NTT in multi-thread
\
This NTT is also based on the research paper, but implements parallelism with rayon.

```rust
#[cfg(feature = "parallel")]
fn forward_ntt_multi(
    params: &RingParams, //Same, the use the parameters, the polynomial and the precalculated twiddles.
    polynomial: &Polynomial,
    ntt_tables: &NTTprecaculated
) -> Polynomial {
    let mut coeffs: Vec<u128> = polynomial.coeffs
        .iter() //We iter, and collect, it's the same thing as in the forward code, but written differently and passing it into u128s
        .map(|&c| c as u128)
        .collect();

    let n = params.n; 
    let q = params.q as u128;

    let mut t: usize = n; //The same
    let mut m: usize = 1;

    loop {
        t = t / 2;

    coeffs
    .par_chunks_mut(2 * t) //We do a par_chunk_mut, which is an operation implemented by rayon which allows us to "cut" the vector into chunks of a size of 2t
    .enumerate()
    .for_each(|(i, chunk)| {  //We treat each chunk in parallel. It's the only thing that changes
        for j in 0..t {
            let u = chunk[j];
            let w = ntt_tables.twiddles[m + i];
            let v = ((chunk[j + t]) * w) % params.q as u128;
            let sum = u + v;
           
            chunk[j] = if sum >= q { sum - q } else { sum }; 

            chunk[j + t] = if u >= v { u - v } else { u + q - v };
        }
    });
   

        m = m * 2;

        if m >= n { break; }
    }

    Polynomial {
        coeffs: coeffs.into_iter().map(|c| c as u64).collect::<Vec<_>>().into_boxed_slice(), //Same thing as in the single-thread code, except the fact that we repass it into u64s
    }
}
```
\
There is no much to say about this function, except the fact that we use a parallelized iteration.
\
\
=== Inverse NTT in single-thread
\
Now that we have our forward NTT function, we need to introduce the inverse NTT function. It's basically the same, except that we use inverse twiddles ($overline(t)$[k]) and that we scale by $n^(-1)$ at the end of the function. The INTT used is also from the _Homomorphic Encryption on GPU_ paper.
\
```rust
fn inverse_ntt_single(
    params: &RingParams, //We use the defined parameters,
    polynomial: &Polynomial, //The polynomial to get back into "normal" domain
    ntt_tables: &NTTprecaculated //The precalculated tables
) -> Polynomial {
    let mut coeffs: Vec<u64> = polynomial.coeffs.to_vec(); 

    let n = params.n;
    let q = params.q as u128;

    let mut t: usize = 1; //This time, t starts with the value of 1.
    let mut m: usize = n; //While m starts with the value of n. (it's the opposite of what we do in the NTT)

    loop {
        let h = m / 2; //Number of groups during this round
        let mut j1: usize = 0; //First bound

        for i in 0..h { //For each group
            let j2 = j1 + t - 1; //the second bound

            for j in j1..=j2 { //For each butterfly in the group
                let u = coeffs[j] as u128;
                let v = coeffs[j + t] as u128;

                let sum = u + v; //We sum then reduce (just like in the NTT)
                let sum = if sum >= q { sum - q } else { sum };
                coeffs[j] = sum as u64;                

                
                let w = ntt_tables.twiddles_inv[h + i]; //But this time, we use the inversed twiddles
                coeffs[j + t] = (((u + q - v) % q * w) % q) as u64;
            }

            j1 += 2 * t;  //We pass to the next group
        }

        t *= 2; //t is multiplied by two, while m is divided by two (exactly the opposite as in the NTT)
        m /= 2; 

        
        if m <= 1 { break; } //When all coefficients are computed, we break
    }

    let n_inv = mod_pow(n as u128, q - 2, q); //Finally, we compute the inverse of n
    for c in coeffs.iter_mut() {
        *c = (*c * n_inv as u64) % q as u64; //And we scale each coefficent with n^(-1)
    }

    Polynomial {
        coeffs: coeffs.into_iter().collect::<Vec<_>>().into_boxed_slice(),
    }
}
```
\
Explanation :
\
\
First, we now that the coeffs that are in the NTT domain (the input coefficients) are in the bit-reversed order : coeffs = $[â_0, â_4, â_2, â_6, â_1, â_5, â_3, â_7]$.
\
We want to recover the original coefficients in standard order.
\
\ 
In the inverse NTT, $t$ starts small and grows, so that :
\
\
t=1:  [0]◄1►[1]  [2]◄1►[3]  [4]◄1►[5]  [6]◄1►[7] 
\
\
t=2:  [0]◄─2─►[2]  [1]◄─2─►[3]  [4]◄─2─►[6]  [5]◄─2─►[7]
\
\
t=4:  [0]◄──1──►[4]  [1]◄──4──►[5]  [2]◄──4──►[6]  [3]◄──4──►[7]
\
\
It's exactly the inverse of the forward NTT.
\
In the INTT, $m$ is the total covered length, while h is the number of groupes :
\
\
$m=8, h=4 => $ 4 groups of butterflies
\
\
$m=4, h=2 => $ 2 groups of butterflies
\
\
$m=2, h=1 => $ 1 groups of butterflies
\
\
Why $h = m slash 2$ ? Because each group contains $t$ butterflies, so that the total number of butterflies is constant ($n slash 2$). So, we need :
\
#align(center)[$h * t = n slash 2)$]
#align(center)[$h = (n slash 2) slash t$]
#align(center)[$h = m slash 2$]
\
\
In the INTT, $j_1$ and $j_2$ are the bounds of the group, like in the NTT, but in another way :
\
For a group $i$ :
\
- $j_1$ is the sum of the length of the previous groups
- $j_2 = j_1 + t - 1$
\
And $j$ is the index of $u$ in each butterfly.
\
\
For example, with $n = 8$, at the second iteration ($t = 2, h = 2$) :
\
\
Group $i = 0$ :
\
#align(center)[$j_1 = 0$]
#align(center)[$j_2 = 0 + 2 - 1 = 1$]
\
#align(center)[Butterflies on coeffs[j]↔coeffs[j + t] and coeffs[j]↔coeffs[j + t].]
#align(center)[Butterflies on coeffs[0]↔coeffs[2] and coeffs[1]↔coeffs[3].]
#align(center)[$j_1 = j_1 + 2*t = 0 + 2 * 2 = 4$]
\
\
\
Group $i = 1$ :
#align(center)[$j_2 = 4 + 2 - 1 = 5$]
\
#align(center)[Butterflies on coeffs[j]↔coeffs[j + t] and coeffs[j]↔coeffs[j + t].]

#align(center)[Butterflies on coeffs[4]↔coeffs[6] and coeffs[5]↔coeffs[7].]
#align(center)[ . . .]
\
\
We can visualize like this, for example :
\
\
Initial state : coeffs = $[â_0, â_4, â_2, â_6, â_1, â_5, â_3, â_7]$.
\
\
Iteration 1 : $t=1$, $h=4, m=8$ :
\                       
\           
#align(center)[Group $i=0$ : $j_1=0, j_2=0$ → $j=0$ : coeffs[0] ↔ coeffs[1] (twiddles[4])]
#align(center)[Group $i=1$ : $j_1=2, j_2=2$ → $j=2$ : coeffs[2] ↔ coeffs[3] (twiddles[5])]
#align(center)[Group $i=2$ : $j_1=4, j_2=4$ → $j=4$ : coeffs[4] ↔ coeffs[5] (twiddles[6])]
#align(center)[Group $i=3$ : $j_1=6, j_2=6$ → $j=6$ : coeffs[6] ↔ coeffs[7] (twiddles[7])]
\                                     
4 groups of 1 butterfly, distance of 1                  
\
\
\
Iteration 2 : $t=2$, $m=2$ : 
\
\                                
Group $i=0$ : $j_1=0$ , $j_2=1$ :                                
#align(center)[j=0 : coeffs[0] ↔ coeffs[2]  (twiddle = twiddles[2])]
#align(center)[j=1 : coeffs[1] ↔ coeffs[3]  (twiddle = twiddles[2])]
\                                                    
Group $i=1$ : $j_1=4$, $j_2=5$                                
#align(center)[j=4 : coeffs[4] ↔ coeffs[6]  (twiddle = twiddles[3])]
#align(center)[j=5 : coeffs[5] ↔ coeffs[7]  (twiddle = twiddles[3])]
\
2 groups of 2 butterflies, distance of 2            
\
Iteration 3 : $t=4$, $h=1$                                  
\
\
Group $i=0$ : $j_1=0$,  $j_2=3$                                
#align(center)[j=0 : coeffs[0] ↔ coeffs[4]  (twiddle = twiddles[1])]
#align(center)[j=1 : coeffs[1] ↔ coeffs[5]  (twiddle = twiddles[1])]
#align(center)[j=2 : coeffs[2] ↔ coeffs[6]  (twiddle = twiddles[1])]
#align(center)[j=3 : coeffs[3] ↔ coeffs[7]  (twiddle = twiddles[1])]
\
4 groups of 1 butterfly, distance of 1                  

Result : coeffs = $[a_0, a_1, a_2, a_3, a_4, a_5, a_6, a_7]$ (normal order)
\
\
Why the twiddles_inv[h + i] ? Because the access to the twiddles follows the structure of the groups (see above). 
\
\
Finally, you can see that the inverse NTT is the exact implementation of the mathematical formula ($omega^(- i hyph.point j)$ in the butterflies and $n^(-1)$ at the end), and the exact opposite of the computation of butterflies (opposite to the computation in the forward NTT).
\
\
=== Inverse NTT in multi-thread
\
We can now also implement a parallelized version of the inverse NTT algorithm :
\
```rust 
#[cfg(feature = "parallel")]
fn inverse_ntt_multi(
    params: &RingParams,
    polynomial: &Polynomial,
    ntt_tables: &NTTprecaculated
) -> Polynomial {
    let mut coeffs: Vec<u128> = polynomial.coeffs
        .iter()
        .map(|&c| c as u128)
        .collect();

    let n = params.n;
    let q = params.q as u128;

    let mut t: usize = 1; //We use the same parameters, the same base.
    let mut m: usize = n;

    loop {
        let h = m / 2;

    coeffs
    .par_chunks_mut(2 * t) //We "cut" this time also by chunks of 2t
    .enumerate()
    .for_each(|(i, chunk)| {
        let w = ntt_tables.twiddles_inv[h + i]; //Access to the inversed twiddles

        for j in 0..t { //Exactly the same
            let u = chunk[j];
            let v = chunk[j + t];

            let sum = u + v;
            chunk[j] = if sum >= q { sum - q } else { sum };

            chunk[j + t] = ((u + q - v) % q * w) % q;
        }
    });

        t = t * 2;
        m = m / 2;

       
        if m <= 1 { break; }
    }

    let n_inv = mod_pow(n as u128, q - 2, q); //Final scaling
    for c in coeffs.iter_mut() {
        *c = (*c * n_inv) % q;
    }

    Polynomial {
        coeffs: coeffs.into_iter().map(|c| c as u64).collect::<Vec<_>>().into_boxed_slice(),
    }
}
```
\
\
== Polynomial multiplication with NTT <poly_mul_ntt>
\
We can finally implement what we need : the polynomial multiplication using the NTT, which is much more efficient than the naive multiplication. This function is really simple, since we already have done the hard job by implementing the NTT :
\
```rust
#[inline]
pub fn mul_ntt(&self, params: &RingParams, ntt_tables: &NTTprecaculated, polynomial: &Polynomial) -> Polynomial { //Function that computes the product of two polynomials by passing them in NTT domain.
    let a = forward_ntt(params, self, ntt_tables); //First, we pass the polynomials into the NTT domain
    let b = forward_ntt(params, polynomial, ntt_tables);

    let mut c_ntt = Polynomial::zeros(params.n);

    for i in 0..params.n {
        c_ntt.coeffs[i] = ((a.coeffs[i] as u128 * b.coeffs[i] as u128) % params.q as u128) as u64; //Then, we just do a basic pointwise multiplication
    }

    inverse_ntt(params, &c_ntt, ntt_tables) //And we finally get back into the "normal" domain
    
}
```
= Errors
\
In `simple-ring`, I didn't implement Errors in a `errors.rs` file, with an enum (_RingError_ for example), and I didn't make all my functions return a `Result<Polynomial, RingError>`. Why ? Because it would have added more complexity. This implementation has to remain simple to use, as :
\
```rust 
let params = RingParams::new(16, 17, find_valid_omega(16, 17));
let ntt_tables = &precalculate(&params);
let poly = Polynomial::new(vec![2u64; params.n]);
let poly2 = Polynomial::new(vec![4u64; params.n]);
let product = poly.mul_ntt(&params, ntt_tables, &poly2);
```
\
And not :
\
```rust 
let params = RingParams::new(16, 17, find_valid_omega(16, 17));
let ntt_tables = &precalculate(&params);
let poly = Polynomial::new(vec![2u64; params.n]);
let poly2 = Polynomial::new(vec![4u64; params.n]);
let product = poly.mul_ntt(&params, ntt_tables, &poly2).unwrap();
```
Nor 
```rust 
fn main() -> Result<(), RingError> {
let params = RingParams::new(16, 17, find_valid_omega(16, 17));
let ntt_tables = &precalculate(&params);
let poly = Polynomial::new(vec![2u64; params.n]);
let poly2 = Polynomial::new(vec![4u64; params.n]);
let product = poly.mul_ntt(&params, ntt_tables, &poly2)?;
}
```
\
So, I decided to add _assert_eq!()_ in the code, to prevent silent errors. In the case where something is wrong, the code should panic, and explain in details what is the error, without needing a _?_ nor an _unwrap()_.
#pagebreak()
= Glossary
\
#table(
  columns: 2,
  [*Term*], [*Definition*],
  [$R_q$], [Polynomial ring $ZZ_q [X] slash (X^n+1)$],
  [NTT], [Number Theoretic Transform: FFT over finite fields],
  [CBD], [Centered Binomial Distribution: discrete approximation of Gaussian],
  [Twiddle], [Precomputed power of omega: $t_k = omega^k mod q$],
)
#pagebreak()
= References
\
[1] : Özcan, Ali & Ayduman, Can & Türkoğlu, Enes & Savaş, Erkay. (2023). Homomorphic Encryption on GPU. IEEE Access. PP. 1-1. 10.1109/ACCESS.2023.3265583. (#link(("https://eprint.iacr.org/2022/1222.pdf")))
\
\
[2] : Sengupta, B., Gupta, P., & Sengupta, S. (2025). Introduction to Number Theoretic Transform. ArXiv, abs/2509.05884. (#link("https://arxiv.org/pdf/2509.05884"))
\
\
[3] :  Damien Stehlé. Euclidean lattices: algorithms and cryptography. Cryptography and Security [cs.CR]. Ecole normale supérieure de lyon - ENS LYON, 2011. ⟨tel-00645387⟩. (#link("https://theses.hal.science/tel-00645387/"))
\
\
[4] : Fermat's Little theorem, on Wikipedia (#link("https://en.wikipedia.org/wiki/Fermat%27s_little_theorem"))
\
\
[5] : Ring, on Wikipedia (#link("https://en.wikipedia.org/wiki/Ring_(mathematics)"))
\
\
[6] : Avanzi, Roberto. CRYSTALS-Kyber Algorithm Specifications And Supporting Documentation. 2017. (#link("https://pq-crystals.org/kyber/data/kyber-specification-round3-20210131.pdf"))
\
\
[7] : S. Lee, J. Woo, J. Kim and J. H. Park, "Generalized Centered Binomial Distribution for Bimodal Lattice Signatures," in IEEE Access, vol. 13, pp. 2203-2214, 2025, doi: 10.1109/ACCESS.2024.3523521.
keywords: {Gaussian distribution;Standards;Polynomials;Digital signatures;Lattices;Timing;Random variables;Newton method;Hypercubes;Cryptography;Post-quantum cryptography;lattice-based signatures;bimodal;binomial distribution}, (#link("https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10817596"))

