[package]
name = "simple-bfv"
description = "Educational implementation of BFV FHE scheme"  
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["fhe", "bfv", "homomorphic", "cryptography", "educational"]
categories = ["cryptography"]
documentation = "https://docs.rs/simple-bfv" 


[dependencies]
rand.workspace = true
rayon = { workspace = true, optional = true }

simple-ring.workspace = true

[features]
parallel = ["dep:rayon"]
