[package]
name = "simple-ring"
description = "Educational implementation of polynomial rings, NTT, and coefficient sampling for lattice-based cryptography" 
documentation = "https://docs.rs/simple-ring" 
keywords = ["cryptography", "ntt", "polynomial", "ring", "educational"]
categories = ["cryptography", "mathematics"]
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rand.workspace = true
rayon = { workspace = true, optional = true }
shake = "0.1.0"
bytemuck = "1.16"
serde = "1.0.228"
postcard = "1.1.3"


[features]
parallel = ["dep:rayon"]
