#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.1": *
#show: codly-init.with()

#set page(
  paper: "a5",
  margin: (x: 1.8cm, y: 1.5cm),
)
#set text(
  font: "New Computer Modern",
  size: 10pt,
)
#set par(
  justify: true,
  leading: 0.52em,
)

#show title: set text(size: 20pt)
#show title: set align(center)

#title[
  Simply Implementing the BFV Scheme
]
\
#outline(title: [Table of contents])
\
#pagebreak()
= Introduction
\
The BFV (Brakerski/Fan-Vercauteren) is a Fully Homomorphic Encryption scheme (FHE), which allows data to be processed while still encrypted. This means we can perform calculations on secure data without needing to decrypt it first. This scheme is practical and useful for keeping data safe during processing, especially in areas like secure communication and privacy-protecting data analysis (Private Information Retrieval, for example). This implementation is for educational purposes.
\
== Warning
First, I want to warn you about the security of this code. This code *isn't* audited, *isn't* intended for production use, *is* vulnerable to timing-based attacks...
\
So please don't use it seriously. But, you can use it to experiment with BFV encryption, implement an e-voting or PIR with it, for example.
\
Finally : make everything you imagine with it, but *don't* use it with sensitive data.
== Context

BFV implementations already exist, but are often coded in _cpp_#footnote[https://github.com/microsoft/SEAL for example] and, fhe.rs#footnote[https://github.com/tlepoint/fhe.rs], while being the best FHE crate (including BFV) in Rust for now, is not made for educational purposes.
\
\
== Who could be interested ?

This crate is designed for people who are searching for a base code for a BFV implementation, for a documented and non-unsafe code, or for people who want to learn about cryptography and especially Learning with Errors & homomorphic cryptography.
This implementation isn't designed for experts, nor enterprises who want to use BFV encryption, nor people who just want a safe, secure and audited code.
#pagebreak()

== What will this crate do ?
\
In this project, we'll try to implement a
\
\
- RLWE encryption (Key generation, encrypt function, decrypt function)
- FHE operations, such as :
- $C + C$
- $C + P$
- $C * P$
Where $C$ is a ciphertext and $P$ a plaintext.
\
== What will this crate not do ?
\
This crate will not :
\
\
- Implement constant-time equations (be aware of timing attacks !)
- Implement $C * C$, relinearization, nor renormalization.
- Implement SIMD
- Be secured

== Concept of Homomorphic encryption
\
The homomorphic encryption#footnote[https://en.wikipedia.org/wiki/Homomorphic_encryption] allows us to perform computations on encrypted data, without access to the secret key.
For example, it allows to do a sum on two ciphertexts :
\
#align(center)[$D(E(m_1) xor E(m_2)) = m_1+ m_2$]
\Where _D_ is the decryption, _E_ is the encryption, $xor$ is the operation on ciphertexts.
\
\

== RLWE (Ring learning with errors) basics <ring>
\
The RLWE is a complicated mathematical problem, considered as computationally hard, even for quantum computers. It makes some modern algorithms secure. For example, CRYSTALS-Kyber#footnote[https://pq-crystals.org/kyber/] or CRYSTALS-Dilithium#footnote[https://pq-crystals.org/dilithium/] are based on the LWE problem.
The RLWE problem is the LWE problem, but in a commutative ring. It makes BFV secure, and it's based on "the assumed intractability of solving certain computational problems if the size of the problem is large enough and the instance of the problem to be solved is chosen randomly#footnote[https://en.wikipedia.org/wiki/Ring_learning_with_errors#Background]"
It is built on the arithmetic of polynomials with coefficients from a finite field : the ring. This ring, in BFV encryption, is noted as :
#align(center)[$ZZ_q [X]slash(X^n+1)$]
Where :
\

$ZZ_q$ is a set of integers ${0, 1, 2, ..., q -1}$ with arithmetic performed modulo $q$. If $q$ is prime, $ZZ_q$ is finite, otherwise, it's a commutative ring. In the code, all the coefficients are reduced modulo $q$ after each operation.
\

$[X]$ is the polynomial ring construction : $ZZ_q [X]$ denotes the set of all polynomials whose coefficients belong to $ZZ_q$. (The form of the polynomial is $a(x) = a_0X⁰ + a_1X¹ + ... + a_k X^k$ where $a_i in ZZ_q$)
\

And we quotient by the ideal generated by $(X^n + 1)$. In the quotient ring, we have the equality $X^n eq.triple -1$. It is useful, because any polynomial of degree $>= n$ is reduced to a polynomial of degree $< n$ by repeatedly substituting $X^n$ with -1.

\
Now, let's see what the construction of the problem is :
\
\
Let $a_i (x)$ be a random but *known* polynomial with coefficients from all of $ZZ_q [X]slash(X^n+1)$. It will be the server's public key.
\
\
Let $e_i (x)$ be a random and *unknown* polynomial with coefficients from all of $ZZ_q [X]slash(X^n+1)$. We will call this variable the "noise".
\
\
Let $s(x)$ be a *secret* polynomial with small coefficients (bounded by _b_) in the ring. It will be the secret key of the client.
\
\
Let $b_i (x) = (a_i (x) hyph.point s(x)) + e_i (x)$ the client's public  key.
\
\
Under these conditions, recovering the *secret* polynomial $s(x)$ given the pair $(a_i (x), b_i (x))$ is as hard as the degree $n$ of the polynomials and the modulus $q$ are sufficiently large.
\
\
The RLWE code used in this implementation is from the crate `simple-ring`, which you can find at `/simple-crypto-lab/simple-ring/`#footnote[ #link("www.github.com/VRAM-RAM/simple-crypto-lab/simple-ring")]. It is recommended to read the documentation#footnote[#link("www.github.com/VRAM-RAM/simple-crypto-lab/docs/simple-ring.pdf")[Documentation of simple-ring]] of it before reading this one, because it explains mathematical basics, such as rings, polynomial operations, modular exponentiation or NTT, and it also explains the implementation of it in Rust. 

#pagebreak()
Now, in this section, we'll detail all about the rust code, but also detail mathematicals concepts.
= Delving into BFV encryption
\
As you've probably read before, we'll be implementing the BFV (Brakerski-Fan-Vercauteren) encryption scheme in this project.
It is one of the most used schemes in the FHE (Fully Homomorphic encryption) domain.
== 1 - Mathematical basics
\
As we said, BFV is based on the RLWE (Ring learning with errors) problem. The system's security depends on the difficulty to resolve equations in Euclidean lattices.
\
BFV doesn't work over individual bits, but over polynomials. It enables parallelism#footnote[https://en.wikipedia.org/wiki/Single_instruction,_multiple_data]. We define the "polynomials" ring as :

#align(center)[$R = ZZ[X] slash (X^n+1)$]
Where $n$ is a power of 2, every polynomial in R has a maximum degree of $n - 1$, and the polynomial multiplication is done with modulo $(X^n + 1)$,
as $X^n eq.triple -1$.
\
For encryption, we work with the quotient ring $R_q$ defined as :
\
#align(center)[$R_q = R slash (q*R) = ZZ_q [X] slash (X^n + 1)$]
All quotients are reduced modulo $q$ (a really big unsigned integer), so that they are in the set ${0, 1, ..., q- 1 }$.
\
Finally, for "plaintext" data, we define the ring :
\
#align(center)[$R_t = ZZ_t [X] slash (X^N + 1)$]
Where $t$ is the "message" or "plaintext" modulus (for example $t = 2$ for binary or $t = 256$ for UTF-8 encoding). There is one critical condition : $t << q$ ($t$ needs to be *much* less than $q$).


#pagebreak()
== 2 - Security and performance parameters

Before running the code, we need to initialise the parameters :
#table(
  columns: 4,
  [*Parameter*], [*Symbol*], [*Description*], [*Impact*],
  [Degree], [$N$], [Power of 2], [On security and latency],
  [Encryption modulus],
  [$q$],
  [*big* unsigned integer],
  [Determine the impact of the noise, and has an impact on the security of encryption, but also latency. ],

  [Plaintext modulus], [$t$], [*small* unsigned integer], [Determine the values that plaintext coefficients can take.],
  [Scale factor],
  [$Delta$],
  [$floor.l q/t floor.r$],
  [Separate noise and message, and useful to scale plaintext's coefficients into ciphertext's coefficients (we'll see it later).],

  [Bit number], [eta], [unsigned integer], [Determine  the distribution of the noise and noise level.],
)
#pagebreak()
We will define these parameters in our code :

We've decided to create a structure named "BFVParams", which defines the parameters :
#codly(languages: codly-languages)
```rust
#[derive(Clone)]
pub struct BFV {
    pub params: RingParams, //n and q are defined in the RingParams struct, because they belong the mathematical code essentially, while t and eta are cryptographic parameters that don't belong to the mathematical code.
    pub t: u64,
    pub eta: usize,
    pub ntt_precalculated: NTTprecaculated, //For NTT acceleration, we precompute the twiddle factors. (More information in the doc of simple-ring)
}
```
\
During the code, we'll also use the _Polynomial_ struct defined in `simple-ring` :

#codly(languages: codly-languages)
```rust
pub struct Polynomial {
    pub coeffs: Box<[u64]>,
}
impl Polynomial {
    pub fn new(c: Vec<u64>) -> Self {
        Self { coeffs: c.into_boxed_slice() }
    }

    pub fn zeros(n: usize) -> Self {
        Self { coeffs: vec![0u64; n].into_boxed_slice() }
    }
}
```

#pagebreak()
== 3 - Key generation
\
The BFV encryption scheme needs 3 keys : the "server's" public key, the "client's" secret key and the "client's" public key.
\
=== The server's public key $a(x)$ generation
\
To generate the server's public key $a(x)$, we will use the function `generate_uniform_polynomial` from `simple-ring`#footnote[#link("www.github.com/VRAM-RAM/simple-crypto-lab/simple-ring/sampling.rs")], because the coefficients of this key need to be in $[0; q-1]$ uniformly :
\
\
Let $c$ be a coefficient, we have $p(c) = 1/q$.
\
=== The client's secret key : $s(x)$
\
Now, we need a function to generate the secret key of the "client", $s(x)$.
The coefficients of this polynomial are in the coefficient ring, but can only have three values :
\
#align(center)[$S(i) in {-1, 0, 1} mod q$]
\
So, to generate the coefficients, we use the function `generate_small_sample` from `simple-ring`, and then we convert the _Sample_ into a _Polynomial_ in our ring :
#codly(languages: codly-languages)
```rust
let s_sample = generate_small_sample(&params);
let s = s_sample.to_poly(params.q);
```
\
=== The client's public key : $b(x)$
\
Finally, to generate the polynomial $b(x)$ which is the client's public key, we use the formula :
\
#align(center)[$b(x) = (a(x) hyph.point s(x)) + e(x)$]
\
Where $b(x)$ is the client's public key, $s(x)$ is the client's secret key, $a(x)$ is the server's public key and $e(x)$ is the random noise.
\
To compute $b(x)$, we have to use two polynomial operations :  the sum, and the multiplication, which were implemented in `simple-ring`.
\
\
Because the naive multiplication is too slow, instead of using it, we'll use the NTT multiplication. 
\
\
Finally, we have to generate the noise $e(x)$. It is a polynomial with coefficients generated with the CBD (Centered Binomial Distribution).\
The generation function we use is - again - a one implemented in `simple-ring`.
\
\

==== Client's public key generation with polynomial sum, multiplication and CBD noise.
\
Now, we can generate all the keys. \ We translate the formula $b(x) = (a(x) hyph.point s(x)) + e(x)$ into :
#codly(languages: codly-languages)
```rust
impl BFV {
    pub fn generate_keys(&self) -> (Polynomial, Polynomial, Polynomial) { 
        let params = &self.params;
        let ntt_tables = &self.ntt_precalculated;

        let a = generate_uniform_polynomial(params);
        let s = generate_small_sample(params);
        let s = s.to_poly(params.q);
        let e = generate_cbd_sample(params.n, self.eta);
        let e = e.to_poly(params.q);
        let mul = a.mul_ntt(params, ntt_tables, &s);
        let b = mul.sum(params, &e);

        (a, b, s)
    }
}
```
Note that, in the final version, there will be a function _generate_client_public_key_, a function _generate_server_public_key_ and a function _generate_client_secret_key_.
#pagebreak()
== 4 - Plaintext encoding
\
I honestly don't know if doing a part for that is useful, but there is how we implement the plaintext :
\
First, we create a struct `Plaintext` :
#codly(languages: codly-languages)
```rust
pub struct Plaintext {
    pub plain: Polynomial, //The plain is just encoded as a polynomial
    len: usize, //The length of stored data (for example : if the plaintext is "Hello", we store 5 bytes with t >= 256.)
}
```

Then, we implement the encoding for the plaintext :
#codly(languages: codly-languages)
```rust
impl Plaintext {
    pub fn new(text: &str, bfv: &BFV) -> Self { //Function that creates a plaintext, given a text in ASCII or UTF-8
        let n = bfv.parameters.n;

        let mut coeffs: Vec<u64> = vec![0; n]; //We create an empty vector

        let bytes = text.as_bytes(); //We turn the text into bytes.

        let len_to_write = bytes.len().min(n); //We deduce the len to write

        for i in 0..len_to_write { //We write the coeffs
            coeffs[i] = bytes[i] as u64;
        }

        Self {
            plain: Polynomial::new(coeffs), //We finally create the Plaintext
            len: len_to_write, 
        }
    }
}
```
It is useful, for debugging or to use BFV on numbers, to have a method that creates the plaintext from raw coefficients :
#codly(languages: codly-languages)
```rust
pub fn new_from_coeffs(coeffs: Vec<u64>, bfv: &BFV) -> Self { //Function to create a plaintext, but directly from a Vec of u64s, not from a String
    Self { plain: Polynomial::new(coeffs), len: bfv.parameters.n }
}
```
If a plaintext is not totally full (for example, with text "Hello" and $n = 4096$, the plaintext contains $5/4096$ coefficients.), it could be useful to "push" coefficient inside of it :
#codly(languages: codly-languages)
```rust
impl Plaintext {
    pub fn push(mut self, to_push: &str) -> Self { //Method to push data into a plaintext

        let encoded: Vec<u64> = to_push.as_bytes().iter().map(|&b| b as u64).collect(); //First, we encode the data into a Vec of u64s

        let remaining = self.plain.coeffs.len() - self.len; //We calculate the remaining coeffs we can write

        let len_to_write = encoded.len().min(remaining); 

        for i in 0..len_to_write { //We write the empty coefficients with pushed ones
            self.plain.coeffs[self.len + i] = encoded[i];
        }

        self.len += len_to_write; //We finally update the len of the plaintext
        self
    }
}
```

\
\
Finally, we need to decode the coefficients, so we implement a function for that :
#codly(languages: codly-languages)
```rust
pub fn decode(&self) -> String { //Method to decode a plaintext
    let vec = self.plain.coeffs.to_vec();
    let vec: Vec<u8> = vec.iter().map(|&b| b as u8).collect();
    str::from_utf8(&vec).unwrap().to_string() //Doing a .unwrap() is a little brutal, and can make the code panic, so I'll implement Errors.
} 
```
\
== 5 - Encryption
\
Now, let's encrypt the message.
\
\
Let $u$ be a polynomial with small coefficients (such as $s$).
\
\
Let $e_1, e_2$ be two polynomials, with "CBD noise" as coefficients.
\
\
Let $Delta = floor.l q/t floor.r$
\
\
Let $m$ be the message we want to cipher.
\
\
Let $a, b$ be the keys generated before.
\
\
The encryption is noted as :
\
#align(center)[$c_0 = ((b hyph.point u) + e_1) + (Delta hyph.point m)$]
#align(center)[$c_1 = (a hyph.point u) + e_2$]
Where :
\
\
+ $b hyph.point u$ and $a hyph.point u$ are a polynomial multiplications, which add noise to the system.
+ $+ e_1, + e_2$ are polynomial sums, which also adds noise to the system.
+ $Delta hyph.point m$ is a polynomial scaling, which encodes the message.
Then, we return the two ciphertexts ${c_0, c_1}$.
\
\
For that, we create a struct called `Ciphertext` which will contain $c_0$ and $c_1$ :
\
#codly(languages: codly-languages)
```rust
#[derive(Debug, Clone)]
pub struct Ciphertext {
    pub c0: Polynomial,
    pub c1: Polynomial,
}
```
\
Then, we implement the formula in Rust :
#codly(languages: codly-languages)
```rust
impl BFV {
    pub fn encrypt(&self, message: &BFVPlaintext, public_key: (&Polynomial, &Polynomial)) -> BFVCiphertext {
        let params = &self.params;
        let ntt_tables = &self.ntt_precalculated;
        let (a, b) = public_key; //We "extract" the keys from the public keypair
        
        let u = generate_small_sample(params); //We generate a noise made out of small coefficients
        let u = u.to_poly(params.q); //We "pass" it into our ring

        let e1 = generate_cbd_sample(params.n, self.eta); //We generate noise with a Centered Binomial Distribution,
        let e1 = e1.to_poly(params.q); //Then "pass" it too into the ring

        let e2 = generate_cbd_sample(params.n, self.eta); //Same
        let e2 = e2.to_poly(params.q);
        
        let delta = params.q / self.t; //We compute delta
        
        let bu = b.mul_ntt(params, ntt_tables, &u); //We compute b * u
        let delta_m = message.plain.scale(params, delta); //We encode the plaintext by scaling it
        let c0_temp = bu.sum(params, &e1); //We continue computing : b * u + e1
        let c0 = c0_temp.sum(params, &delta_m); //We finish computing c0 : (b * u + e1) + delta * m
        
        let au = a.mul_ntt(params, ntt_tables, &u); //We compute c1 in two steps. First, we do a * u,
        let c1 = au.sum(params, &e2); //Then we compute a * u + e2

        BFVCiphertext { c0, c1 } //We finally return the Ciphertext
    }
}
```
\
== 6 - Decryption
\
To decrypt the two ciphertexts ${c_0, c_1}$, we need to have the secret key $s$.
\
The decryption formula is :
\

#align(center)[Let $m prime = c_0 - c_1 hyph.point s$]
\
We develop :
\
\
#align(center)[$m prime = (b hyph.point u + e_1 + Delta hyph.point m) - (a hyph.point u + e_2) hyph.point s$ ]
\
We replace $b$ by $a(x) hyph.point s(x) + e$ :
\
\
#align(
  center,
)[$m prime = (a hyph.point s +e) hyph.point u + e_1 + Delta hyph.point m - (a hyph.point u + e_2)hyph.point s$]
\
#align(
  center,
)[$m prime = (a hyph.point s hyph.point u) + e hyph.point u + e_1 + Delta hyph.point m - (a hyph.point u + e_2)hyph.point s$]
\
#align(
  center,
)[$m prime = (a hyph.point s hyph.point u) + e hyph.point u + e_1 + Delta hyph.point m - a hyph.point s hyph.point u - e_2 hyph.point s$]
\
#align(center)[$m prime = e hyph.point u + e_1 + (Delta hyph.point m) - e_2 hyph.point s$]
\
And so we have :
\
#align(center)[$m prime = (Delta hyph.point m) +$ noise]
\
Because $e hyph.point u$, $e_1$, $e_2 hyph.point s$ are really small.
\
We want now to extract the message from $m prime$.
\
\
#align(center)[$r = floor.l t/q hyph.point m prime ceil.r mod t$]
\
Where $m prime$ is the message + the noise, $r$ is the recovered message.
\
\
Proof :
\
\
We know that :

#align(center)[$m prime tilde.eq Delta hyph.point m$]
\
And that :
\
#align(center)[$Delta = floor.l q/t floor.r$]

So :
#align(center)[$r tilde.eq floor.l t/q hyph.point Delta hyph.point m ceil.r mod t$]
And :
#align(center)[$r tilde.eq floor.l t/q hyph.point floor.l q/t floor.r hyph.point m ceil.r mod t$]
Finally :
#align(center)[$r tilde.eq 1 hyph.point m mod t$]
We reduce it by $t$ because the message is in $R_t (ZZ slash (X^n + 1) mod t).$
The rounded $floor.l ceil.r$ is used to "erase" the noise, so we have the original message. Note that for this to work, the noise needs not to be too strong (it has to be $< Delta/2$).

#pagebreak()
Now, let's implement this in Rust :
#codly(languages: codly-languages)
```rust
pub fn decrypt(&self, ciphertext: &Ciphertext, secret_key: &Polynomial) -> String {
    let params = &self.parameters;
    let ntt_tables = &self.precalculated;

    //First, we compute m_prime = c0 - c1 * s
    let c1s = Polynomial::polynomial_mul_ntt(params, ntt_tables,&ciphertext.c1, secret_key);
    let m_prime = Polynomial::polynomial_sub(params, &ciphertext.c0, &c1s);

    let mut coeffs = vec![0u64; params.n];
    let q = params.q as i128;
    let t = params.t as i128;
    //Then, for each coefficient, we "erase" the noise. It's the most delicate part of the decryption. See below for explanation.
    for i in 0..params.n {
        let raw = m_prime.coeffs[i] as i128;

        let val = if raw > q / 2 { raw - q } else { raw };

        let decoded = ((val * t + q / 2).div_euclid(q) % t + t) % t;

        coeffs[i] = decoded as u64;
    }


    Plaintext { plain: Polynomial::new(coeffs), len: params.n }.decode()
}
```
Well, it couldn't be as easy as just applying the mathematical formula. The problem is that if, when decoding, we remain in $ZZ_q$, the noise will not be erased, so we have to change of representation. At line 14, we first make $m prime$ as integer, because it is, at line 16, centered in $(-q slash 2; q slash 2]$.
\
\
Why do we center? Because the value $m'$ is computed modulo $q$, so it satisfies:
#align(center)[
  $m' equiv tilde(m') mod q$
]
\
which means that there exists an integer $k$ such that:
\
#align(center)[
  $tilde(m') = m' + k dot q$
]
\
Moreover, we have:
#align(center)[
  $tilde(m') = Delta dot m + e$
]
\
Without centering, we may use a representative of $m'$ that is far from $tilde(m')$, leading to:
\
#align(center)[
  $r = floor.l t/q dot (Delta dot m + e - k dot q) ceil.r$
]
\
which introduces an unwanted term $k t$ after scaling.
\
\
With centering, we ensure that we use the representative of $m'$ that is closest to $tilde(m')$. We then compute:
\
#align(center)[
  $r = floor.l t/q dot m' ceil.r mod t$
]
\
Since:
#align(center)[
  $m' approx Delta dot m + e = q/t dot m + e$
]

we obtain:
\
#align(center)[
  $r = floor.l m + (t/q) dot e ceil.r mod t$
]

If the noise $e$ is small enough, the rounding removes it and we recover:
\
\
#align(center)[
  $r = m mod t$
]
\
Hence:
\
#align(center)[
  $r = m in R_t$
]
\
#pagebreak()
== 7 - Homomorphic operations
\
The core of BFV is the operations we can compute on ciphertexts. There are 4 operations (well in fact many more, like _relinearization_, _normalisation_, _modulo switching_... but these operations won't be used nor implemented here). The main operations in BFV are :

+ The sum of a plaintext and a ciphertext $C + P$,
+ The sum of two ciphertexts $C + C$,
+ The product of one ciphertext and one plaintext $C*P$,
+ The product of two ciphertexts $C*C$

Implementing these operations isn't difficult, except for the fourth one, the product of two ciphertexts, because, during the product of two ciphertexts, the degree of the polynomials changes, so we have to introduce _relinearization_, but also the noise grows exponentially, so we have to introduce _normalization_. But, even with these two operations, without implementing the _RNS_#footnote[#link("https://en.wikipedia.org/wiki/Residue_number_system")] (Residue Number System), implementing the product is too difficult, and technically impossible (the performance is affected if _RNS_ isn't implemented).
\
If you're interested in it, please see the documentation at the end of the document.
\

=== Sum of two ciphertexts ($C + C$)
\
In the BFV FHE scheme, the most simple operation to implement is the sum of two ciphertexts, because it's just a polynomial sum computed on the two ciphertexts. We implement it as a method of BFV :
#codly(languages: codly-languages)
```rust
impl BFV {
    pub fn sum_ciphertexts(&self, first_cipher: Ciphertext, second_cipher: Ciphertext) -> Ciphertext {
        let params = &self.parameters;
        let new_c0 = first_cipher.c0.sum(params, &second_cipher.c0); 
        let new_c1 = first_cipher.c1.sum(params, &second_cipher.c1);
        Ciphertext { c0: new_c0, c1: new_c1 }
    }
}
```
#pagebreak()
=== Sum of a plaintext and a ciphertext ($C + P$)
\
The sum of a plaintext and a ciphertext is not as simple as the sum of two ciphertexts, because :
+ The plaintext is not scaled like the message $m$ which was scaled by $Delta$.
+ The plaintext is compound by a polynomial, but the ciphertext is compound by two polynomials.

\
First, we scale the plaintext :
\
#align(center)[$p prime = p hyph.point Delta$]
\
Then, we do :
\
#align(center)[$c_0 prime = c_0 + p prime$]
#align(center)[$c_1 prime = c_1$]
\
And the sum is done !
\
\
Proof :
\
Let $m$ be the initial message, $p$ be a plaintext we sum, $b, a, s$ the keys and $u, e$ the noises :
\
\
#align(center)[$c_0 = ((b hyph.point u) + e_1) + (Delta hyph.point m)$]
#align(center)[$c_1 = (a hyph.point u) + e_2$]
\
\
#align(center)[$c_0 prime = c_0 + p hyph.point Delta$]
#align(center)[$c_1 prime = c_1$]
\
\
So, in decryption :
#align(center)[Let $m prime = c_0 prime - c_1 prime hyph.point s$]
\
\ 
We develop :
\
\
#align(center)[$m prime = (b hyph.point u + e_1 + Delta hyph.point m) + p hyph.point Delta - (a hyph.point u + e_2) hyph.point s$ ]
\
We replace $b$ by $a(x) hyph.point s(x) + e$ :
\
\
#align(
  center,
)[$m prime = (a hyph.point s +e) hyph.point u + e_1 + Delta hyph.point m + p hyph.point Delta - (a hyph.point u + e_2)hyph.point s$]
\
#align(
  center,
)[$m prime = (a hyph.point s hyph.point u) + e hyph.point u + e_1 + Delta hyph.point m + p hyph.point Delta - (a hyph.point u + e_2)hyph.point s$]
\
#align(
  center,
)[$m prime = (a hyph.point s hyph.point u) + e hyph.point u + e_1 + Delta hyph.point m + p hyph.point Delta - a hyph.point s hyph.point u - e_2 hyph.point s$]
\
#align(center)[$m prime = e hyph.point u + e_1 + (Delta hyph.point m) + (p hyph.point Delta) - e_2 hyph.point s$]
And so we have :
#align(center)[$m prime = (Delta hyph.point m) + (Delta hyph.point p) +$ noise]
\
Finally :
#align(center)[$r = floor.l t/q hyph.point m prime ceil.r mod t$]
\
#align(center)[$r = floor.l t/q hyph.point [(Delta hyph.point m) + (Delta hyph.point p)] + $ noise$ ceil.r mod t$]
\
#align(center)[$r = floor.l t/q hyph.point [(q/t hyph.point m) + (q/t hyph.point p)] + $ noise$ ceil.r mod t$]
\
#align(center)[$r = floor.l t/q hyph.point [(q/t hyph.point m) + (q/t hyph.point p)] + $ noise$ ceil.r mod t$]
\
#align(center)[$r = floor.l m + p + $noise$ ceil.r mod t$]
\
#align(center)[$r = m + p mod t$]
\
We can now implement it in our code :
#codly(languages: codly-languages)
```rust
impl BFV {
    pub fn sum_ciphertext_and_plaintext(&self, ciphertext: &Ciphertext, plaintext: &Plaintext) -> Ciphertext { //Function to sum a ciphertext and a plaintext
        let params = &self.parameters;
        let delta = params.q / params.t; 
        let delta_m = plaintext.plain.scale(params, delta); //We first need to scale the plaintext coeffs with delta
        let new_c0 = ciphertext.c0.sum(params, &delta_m); //Then we can sum, but only on c0, not on c1
        let new_c1 = ciphertext.c1.clone();

        Ciphertext { c0: new_c0, c1: new_c1 }
    }
}
```
\
=== Product of a ciphertext and a plaintext ($C * P$)
\
The product of a ciphertext and a plaintext is the last operation we'll implement in this implementation. It is as simple as $C + C$, because the formula of this product is :
\
#align(center)[$c_0 prime = c_0 hyph.point p$]
#align(center)[$c_1 prime = c_1 hyph.point p$]
\
Here, we don't have to scale nor to apply it on only one coefficient, it's really intuitive.
\
\
Proof :
\
Let $m$ be the initial message, $p$ be a plaintext we multiply, $b, a, s$ the keys and $u, e$ the noises :
\
\
#align(center)[$c_0 = ((b hyph.point u) + e_1) + (Delta hyph.point m)$]
#align(center)[$c_1 = (a hyph.point u) + e_2$]
\
\
#align(center)[$c_0 prime = c_0 hyph.point p$]
#align(center)[$c_1 prime = c_1 hyph.point p$]
\
\
So, in decryption :
#align(center)[Let $m prime = c_0 prime - c_1 prime hyph.point s$]
\
\ 
We develop :
\
\
#align(center)[$m prime = (b hyph.point u + e_1 + Delta hyph.point m) hyph.point p - (a hyph.point u + e_2) hyph.point s hyph.point p$ ]
\
We replace $b$ by $a(x) hyph.point s(x) + e$ :
\
\
#align(
  center,
)[$m prime = (a hyph.point s + e) hyph.point u hyph.point p + e_1 hyph.point p + Delta hyph.point m hyph.point p - (a hyph.point u + e_2)hyph.point s hyph.point p$]
\
#align(
  center,
)[$m prime = (a hyph.point s hyph.point  u hyph.point p) + e hyph.point u hyph.point p + e_1 hyph.point p + Delta hyph.point m hyph.point p - (a hyph.point u + e_2)hyph.point s hyph.point p$]
\
#align(
  center,
)[$m prime = (a hyph.point s hyph.point u hyph.point p) + e hyph.point u hyph.point p + e_1 hyph.point p + Delta hyph.point m hyph.point p - a hyph.point s hyph.point u hyph.point p - e_2 hyph.point s hyph.point p$]
\
#align(center)[$m prime = e hyph.point u hyph.point p + e_1 hyph.point p + (Delta hyph.point m hyph.point p) - e_2 hyph.point s hyph.point p$]
And so we have :
#align(center)[$m prime = (Delta hyph.point m hyph.point p) +$ noise]
\
Finally :
#align(center)[$r = floor.l t/q hyph.point m prime ceil.r mod t$]
\
#align(center)[$r = floor.l t/q hyph.point (Delta hyph.point m hyph.point p) + $ noise$ ceil.r mod t$]
\
#align(center)[$r = floor.l t/q hyph.point (q/t hyph.point m hyph.point p) + $ noise$ ceil.r mod t$]
\
#align(center)[$r = floor.l m hyph.point p + $noise$ ceil.r mod t$]
\
#align(center)[$r = m hyph.point p mod t$]
\
As you can see, in this operation, the noise is scaled by $p$ three times, so it becomes louder, while in the sum the noise wasn't affected by the sum. It means that, after many products, the noise can be too loud so that the message doesn't decrypt correctly.
\
\
Now, let's implement it in our code :
#codly(languages: codly-languages)
```rust
impl BFV {
    pub fn mul_ciphertext_and_plaintext(&self, ciphertext: &Ciphertext, plaintext: &Plaintext) -> Ciphertext { 
        let params = &self.parameters;
        let ntt_tables = &self.precalculated;
        let new_c0 = ciphertext.c0.mul_ntt(params, ntt_tables, &plaintext.plain);
        let new_c1 = ciphertext.c1.mul_ntt(params, ntt_tables, &plaintext.plain);

        Ciphertext { c0: new_c0, c1: new_c1 }
    }
}
```
#pagebreak()

== 8 - Noise Management
\
In BFV, noise is intentional: it provides security via the RLWE assumption. But it is also a constraint : if noise grows too large, decryption fails.

This section focuses on how noise behaves in the operations we implemented ($C+C$, $C+P$, $C times P$), without advanced techniques like RNS or bootstrapping.

=== 8.1 Noise in a Ciphertext
\
After encryption, a ciphertext $(c_0, c_1)$ satisfies:
\
\
#align(center)[$[c_0 + c_1 times s]_q = Delta times m + e_(t) (mod q)$]
\
Where $e_(t) = e_1 + e_2 times s + e times u$ combines:
#table(
  columns: 1,
  [$e_1, e_2$: CBD-sampled noise polynomials],
  [$e$: small error from the public key $b = -a times s + e$],
  [$u$: small random polynomial used during encryption],
)

All components are small, so $e_(t)$ starts small.

=== 8.2 Decryption Condition
\
Decryption computes:
\
#align(center)[$m' = floor.l (t/q) times [c_0 + c_1 times s]_q ceil.r (mod t)$]
\
This recovers $m$ correctly #strong[only if]:
\
\
#align(center)[$||e_(t)||_infinity < Delta/2$]
\
where $Delta = floor.l q/t floor.r$ and $||dot.c||infinity$ is the maximum absolute coefficient.
\
If noise exceeds $Delta/2$, rounding crosses a boundary and decryption returns a wrong value, silently.
#pagebreak()
=== 8.3 Noise Growth in Our Operations
\
#table(
  columns: 3,
  [*Operation*], [*Noise growth*], [*Rough limit*],
  [$C + C$], [Additive: $||e_1|| + ||e_2||$], [~50–100 additions],
  [$C + P$], [None: $||e||$ unchanged], [Unlimited],
  [$C times P$], [Multiplicative: $||p|| times ||e||$], [~5–10 multiplications],
)

These limits assume typical parameters ($q approx 2^19$, $t = 256$, $eta = 8$).
Adjust based on your chosen $q$, $t$, and $eta$.
\
\
=== 8.4 Working Within Limits
\
Since our implementation does not include RNS, modulus switching, or bootstrapping:
\

- #strong[Plan depth ahead:] Count multiplications; keep sequential $C times P$ operations low.
  
  
- #strong[Prefer small plaintexts:] Use $t = 2$ (binary) for heavy computations to limit noise scaling.
  
  
- #strong[Monitor during development:] Optionally compute $||[c_0 + c_1 times s]_q - Delta times m||_infinity$ to estimate noise (educational use only), with the function `estimate_noise`.

  
- #strong[Re-encrypt if possible:] If you hold the secret key, decrypting and re-encrypting resets noise.
  


=== 8.5 Summary
\
#block(
  fill: luma(98%),
  stroke: (left: 2pt + blue),
  inset: 8pt,
  [
    #strong[Key takeaways:]
      \
      Noise is required for security but must stay below $Delta/2$ for correct decryption. \
      Addition grows noise slowly; multiplication grows it faster. \
      Without RNS or bootstrapping, computation depth is limited—plan accordingly. \
      For production use, consider libraries with advanced noise management (SEAL, OpenFHE).
    
  ]
)

#pagebreak()
= References
\
[1] : Fan, Junfeng and Frederik Vercauteren. “Somewhat Practical Fully Homomorphic Encryption.” IACR Cryptol. ePrint Arch. 2012 (2012): 144. (#link("https://eprint.iacr.org/2012/144.pdf"))
\
\
[2] : Mali, B. Raut. “Generalized BGV, BFV, and CKKS for Homomorphic Encryption over Matrix Rings.” IACR Cryptol. ePrint Arch. 2025 (2025): 972. (#link("https://eprint.iacr.org/2025/972.pdf"))
\
\
[3] : Homomorphic encryption on Wikipedia (#link("https://en.wikipedia.org/wiki/Homomorphic_encryption"))
\
\
[4] : Özcan, Ali & Ayduman, Can & Türkoğlu, Enes & Savaş, Erkay. (2023). Homomorphic Encryption on GPU. IEEE Access. PP. 1-1. 10.1109/ACCESS.2023.3265583. (#link("https://eprint.iacr.org/2022/1222.pdf"))
\
\
[5] : Inferati Inc., “Introduction to the BFV FHE Scheme.” [Online]. Available: PDF document. (#link("https://faculty.kfupm.edu.sa/coe/mfelemban/SEC595/References/Introduction%20to%20the%20BFV%20FHE%20Scheme.pdf"))
\
\
[6] : Linus Tang, “BFV Homomorphic Encryption: Part 1,” Massachusetts Institute of Technology. [Online]. Available: #link("https://www.mit.edu/~linust/files/BFV_Homomorphic_Encryption_Part_1.pdf"). [Accessed: May 16, 2026].