#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.1": *
#show: codly-init.with()

#set page(
  paper: "a5",
  margin: (x: 1.8cm, y: 1.5cm),
)
#set text(
  font: "New Computer Modern",
  size: 10pt,
)
#set par(
  justify: true,
  leading: 0.52em,
)

#show title: set text(size: 20pt)
#show title: set align(center)

#title[
  #text(size: 32pt, weight: "bold")[simple-ring]
  #v(0.1em)
  #text(size: 14pt, fill: luma(30%))[\
  Mathematical Primitives for Lattice-Based Cryptography]
  #v(0.7em)
  #text(size: 11pt, fill: luma(40%), style: "italic")[\
  An Educational Implementation for Learning and Experimentation]
]


\
#outline(title: [Table of contents])
\
#pagebreak()
= Introduction
\
#emph[This document describes simple-ring, an educational implementation of
mathematical primitives for lattice-based cryptography.]

Modern post-quantum cryptography (BFV, CKKS, Kyber, Dilithium) relies on the
polynomial ring $Z_q = Z_q [X] slash (X^n + 1)$. Understanding this structure
is essential for working with these schemes, but research papers are often complicated, and are often not written for educational purposes, especially in Rust.

#strong[Goal:] Bridge the gap between abstract mathematics and concrete implementation.

== Warning
\
Before everything, I wanted to warn you about the security of this code. This code *isn't* audited, *isn't* made to be used seriously, *is* vulnerable to timing-based attacks...
\
So please don't use it in vulnerable environments. But, you can use it to experiment with schemes, you can re-use the NTT, the polynomial code... as you want.
\
Make everything you imagine with it, but *don't* use it with sensible datas.
\

== What's inside ?
\
`simple-ring` provides:
\
\
+ Polynomials in $Z_q$,
+ NTT/INTT for fast multiplication,
+ Modular arithmetic,
+ Sampling methods (CBD, Uniform)



== How to read it ?
\
This documentation revolves around the structure of the crate, and a "progression". First, we'll introduce mathematical basics, then will explain the Rust code; in details.
\
#pagebreak()

= `ring.rs` : The Ring
\
== Congruence
\
First, let's introduce mathematical basics. The symbol "$equiv$" means "is congruent to" ("est congru à" in french), which means :
\
#align(center)[$a equiv b (mod n) arrow.l.r.double (a mod n) = (b mod n)$]
\
For example, if we have $a = 5$, $b = 17$, $q = 12$ :
\
#align(center)[$a mod q = 5 mod 12 = 5$]
#align(center)[$b mod q = 17 mod 12 = 5$]
\
So $a equiv b mod q$.
\
\
== What is a Ring ?
\
A ring is a mathematical structure where you can :
\
\
+ Add elements (integers for example),
+ Substract elements (addition has inverses),
+ Multiply elements (distributive over additions)
\
Think it as a structure where you can define operations and rules.

The formal definition of a commutative ring is a set $R$ equipped with two operations : addition and multiplication.
#table(
  columns: 3,
  [*Property*], [*Addition*], [*Multiplication*],
  [Closure], [$a + b in R$], [$a * b in R$],
  [Assiociativity], [$(a+b)+c = a+(b+c)$], [$(a*b) * c = (b*c)*a$],
  [Identity], [$exists 0, a + 0 = a$], [$exists 1, a * 1 = a$],
  [Inverses], [$forall a, exists -a, a + (-a) = 0$], [Not always],
  [Commutativity], [$a + b = b + a$], [$a * b = b * a$],
  [Distributivity], [], [$a * (b + c) = a * c + a * b$],
)

If the multiplication is not commutative, it's a *non-commutative ring*. If there's no multiplicative identity, it's a *pseudo-ring*, and not a ring.
\
\
== The ring used in cryptography
\
In lattice-based cryptography, such as *BFV* or *Kyber*, all the computations are done in a commutative ring. It is noted as :
#align(center)[$ZZ_q [X]slash(X^n+1)$]
Where :
\

$ZZ_q$ is a set of integers ${0, 1, 2, ..., q -1}$ with arithmetic performed modulo $q$. $ZZ_q$ is always a finite commutative ring with $q$ elements. 
If $q$ is prime, $ZZ_q$ is additionally a #strong[field] (every non-zero element has a multiplicative inverse). In the code, all the coefficients are reduced modulo $q$ after each operation.
\

$[X]$ is the polynomial ring construction : $ZZ_q [X]$ denotes the set of all polynomials whose coefficients belong to $ZZ_q$. (The form of the polynomial is $a(x) = a_0X⁰ + a_1X¹ + ... + a_k X^k$ where $a_i in ZZ_q$).
\

Finally, we quotient by the ideal generated by $(X^n + 1)$. In the quotient ring, we have the equality $X^n equiv -1$. It is useful, because any polynomial of degree $>= n$ is reduced to a polynomial of degree $< n$ by repeatedly substituting $X^n$ with -1.
\
\
In our Rust code, we implement a structure for the ring :

#codly(languages: codly-languages)
```rust
//ring.rs
#[derive(Clone)]
pub struct RingParams {
    pub n: usize, //The length of the polynomial, in usize.
    pub q: u64, //The modulus
    pub omega: u64, //omega, for the NTT (we'll see it in ntt.rs)
}
impl RingParams { 
    pub fn new(n: usize, q:u64, omega: u64) -> Self {
        Self { n, q, omega }
    }
}
```

#pagebreak()

= `polys.rs` : The polynomials in $ZZ_q [X]slash(X^n+1)$
\
In `simple-ring`, the polynomials "live" in the ring. To implement polynomials in Rust, we simply create a struct `Polynomial` which contains a `Box` of an array of u64s :

#codly(languages: codly-languages)
```rust
pub struct Polynomial {
    pub coeffs: Box<[u64]>,
}

impl Polynomial {
    pub fn new(c: Vec<u64>) -> Self { 
        Self { coeffs: c.into_boxed_slice() }
    }

    pub fn zeros(n: usize) -> Self {
        Self { coeffs: vec![0u64; n].into_boxed_slice() }
    }
}
```

The `new` function allows you to create a polynomial from a `Vec<u64>`, while the `zeros` function allows you to create an empty polynomial of length $n$, $n$ being the value stored in `RingParams`.

== Polynomial operations
\
Now that we have a basic type for the polynomials, we can implement methods for basic polynomial operations, which will be useful when implenting cryptographic schemes.

=== Polynomial sum
\
The most simple operation to implement is the polynomial sum in $ZZ_q [X]slash(X^n+1)$. The sum is defined by :
\
#align(center)[$S_k = A_k + B_k mod q$]
\
Where $A$ and $B$ are two polynomials and $S$ is their sum.
\
We can easily code it, with this simple function :
\
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    fn polynomial_sum_single(params: &RingParams, first: &Self, second: &Self) -> Self { //The single-thread sum.
        let mut coeffs = vec![0u64; params.n];
        for i in 0..params.n {
            coeffs[i] = ((first.coeffs[i] as u128 + second.coeffs[i] as u128) % params.q as u128) as u64;
        }
        Polynomial::new(coeffs)
    }
}
```
In this code, we implement, for the struct _Polynomial_, the function _polynomial_sum_single_ which does the sum of two polynomials, and then represent their coefficient modulo $q$ in $ZZ_q$. Yes, I could have done something like coeffs[i].wrapping_add(...), or do something like .iter().zip(...) but it is less readable than the simple "+" operator, and the goal is here to provide a simple and readable code.
\
\
In this crate, I also wanted to implement a parallelized code. So, I used the crate `rayon`, and create a function called _polynomial_sub_multi_ which does gives exactly the same result as the _polynomial_sum_single_; but theorically more faster. In fact, I didn't notice any difference in term of performances (and sometimes the parallelized version was worst than the single-thread one). Anyway, there is the code for the parallel version : 
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[cfg(feature = "parallel")]
    fn polynomial_sum_multi(params: &RingParams, first: &Self, second: &Self) -> Self { 
        let mut coeffs = vec![0u64; params.n];
        coeffs
            .par_iter_mut() //I use the parallelized iter, provided by rayon.
            .enumerate()
            .for_each(|(i, coeff)| {
                *coeff = ((first.coeffs[i] as u128 + second.coeffs[i] as u128) % params.q as u128) as u64;
            });
        Self { coeffs: coeffs.into_boxed_slice() }
    }
}
```
=== Polynomial substraction
\
The polynomial substraction, in our ring, is noted as :
#align(center)[$S_k = A_k - B_k mod q$]
\
So it's slightly the same thing as the sum. We write it in Rust :
```rust
#[inline]
fn polynomial_sub_single(params: &BFVParams, first: &Self, second: &Self) -> Self {
    let mut coeffs = vec![0u64; params.n];
    for i in 0..params.n {
        coeffs[i] = ((first.coeffs[i] as i128 - second.coeffs[i] as i128).rem_euclid(params.q as i128)) as u64 ; //We convert into i128 so that we don't have an underflow. The rem_euclid makes the result remain euclidean, so that it is in the ring.
    }
    Polynomial::new(coeffs)
}
```
Here, the only thing to be aware of is the fact that u64 - u64 can underflow, so that we need to convert it into i128s before computing. Also, because the result of u64 - u64 can be negative, we need to compute .rem_euclid() and not %, so that the result remains euclidean (remains positive).
Like for the polynomial sum, I've also implemented a multi-thread function :
```rust
impl Polynomial {
    [cfg(feature = "parallel")]
    fn polynomial_sub_multi(params: &RingParams, first: &Self, second: &Self) -> Self { 
        let mut coeffs = vec![0u64; params.n];
        coeffs.par_iter_mut().enumerate().for_each(|(i, coeff)| {
            *coeff = (first.coeffs[i] as i128 - second.coeffs[i] as i128).rem_euclid(params.q as i128) as u64;
        });

        Self { coeffs: coeffs.into_boxed_slice() }
    }
}
```
\

=== Polynomial multiplication
\
Now, let's introduce a more "complex" function : the polynomial multiplication in $ZZ_q$.
The naive multiplication (not in the  ring) in noted as :
\
#align(center)[$M_k = sum_(i+j=k) A_i *B_j$]
\
Where $A, B$ are two polynomials and $M$ their product.
\
So, let's implement it !
#codly(languages: codly-languages)
```rust
impl Polynomial {
    pub fn polynomial_mul(params: &RingParams, first: &Self, second: &Self) -> Self {
        assert_eq!(first.coeffs.len(), params.n); //We ensure the polynomials have the good length, and that they also have the same length.
        assert_eq!(second.coeffs.len(), params.n);

        let mut b = vec![0u64; 2 * params.n - 2]; //We create a vec, but two times larger (because the product of two polynomials have (2 * n - 2) coefficients.)

        for i in 0..params.n {
            for j in 0..params.n {
                let k = i + j;
                b[k] += first.coeffs[i] * second.coeffs[j];
            }
        }
      Self { coeffs: b.into_boxed_slice() }
}
```
\
This "naive" implementation could be good for a simple polynomial multiplication, but doesn't work for our multiplication in the ring. Also, if $n, q$ are too large, we can have an overflow. So, here are the solutions :
+ To avoid the overflow, we'll simply use u128 and not u64.
+ To have coefficients in the ring, we just reduce them mod q.
+ But the degree of the result of the multiplication doubles, so we get up to 2n−2. It means that the result isn't in $ZZ[x] slash (X^n + 1)$. For example, let's have a polynomial $b_(n+k)X^(n+k)$.
This polynomial goes has this form :
#align(center)[$P(x) = b_0X^0 + b_1X^1 + b_2X^2 + ... + b_(n+k)X^(n+k)$]
\
Where $k$ coefficients are "out" of the ring. Here is how to get them back into it :
\
\
We use the fact that :
\
#align(center)[$X^n + 1 = 0$]
\
#align(center)[$X^n = -1$]
\
So :
\
#align(center)[$X^(n+k) = X^n * X^k$]
\
#align(center)[$X^(n+k) = (-1) * X^k$]
\
#align(center)[$X^(n+k) = -X^k$]
\
In our case, we have :
\
#align(center)[$b_(n+k)X^(n+k) = -b_(n+k)X^k$]
\
\
Now, consider the polynomial after multiplication:
\
\

#align(center)[$b(X) = sum_(i=0)^(2n-2) b_i X^i$]
\

We split it into two parts : a part that fits in the ring, and a part that is out of it [1]:
\
\

#align(center)[$sum_(k=0)^(n-1) b_k X^k + sum_(k=0)^(n-1) b_(k+n) X^(k+n)$]
\

Using the previous result:
\
\

#align(center)[$b_(k+n)X^(k+n) = -b_(k+n)X^k$]
\
\
We have:
\
\

#align(center)[$sum_(k=0)^(n-1) b_(k+n) X^(k+n) = sum_(k=0)^(n-1) (-b_(k+n)) X^k$]
\
We combine both contributions from [1]:
\
\
#align(center)[$b(X) = sum_(k=0)^(n-1) (b_k - b_(k+n)) X^k$]
\

#align(center)[$c_k = b_k - b_(k+n)$]
\

And in $ZZ_q$ :
\
\

#align(center)[$c_k = (b_k - b_(k+n)) mod q$]
\
#pagebreak()
Now, let's implement it in Rust :
\
\
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    pub fn mul(&self, params: &RingParams, polynomial: &Polynomial) -> Self {
        assert_eq!(self.coeffs.len(), params.n);
        assert_eq!(polynomial.coeffs.len(), params.n);
        
        let mut b = vec![0u64; 2 * params.n];
        
        for i in 0..params.n {
            for j in 0..params.n {
                let k = i + j;
                b[k] += self.coeffs[i]  * polynomial.coeffs[j] ; //[1]

            }
        }
        
        let mut coeffs = vec![0u64; params.n];
        for k in 0..params.n { //[2]
            let low = b[k];
            let high = if k + params.n < b.len() { b[k + params.n] } else { 0 };
            
            let val = ((low as i128) - (high as i128)).rem_euclid(params.q as i128) as u64;
            coeffs[k] = val;
        }

        Polynomial::new(coeffs)
    }
  }
```
First, in [1], we do the naive multiplication, and then, in [2], we apply the formula $c_k = (b_k - b_(k+n)) mod q$ (low is $b_k$ and high is $b_(k+n)$). We use .rem_euclid so that it remains euclidean (and we cannot have negative values).
\
\
It's done ! The polynomial multiplication is implemented. But we'll see later that this implementation, being too slow (complexity $O(n^2)$), will be replaced.
\
=== Polynomial scaling
\
Scaling a polynomial is simply noted as :
\
#align(center)[$B_k = (A_k * lambda) mod q$]
\
Where $lambda$ is a constant, $q$ is the modulus, $A_k$ is the polynomial we want to scale and $B_k$ is the result of the scaling. It's easily implementable :
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    pub fn scale(&self, params: &RingParams, lambda: u64) -> Self {
        let coeffs: Vec<u64> = self.coeffs
            .iter() //We iterate for each coefficient
            .map(|&coeff| ((coeff as u128 * lambda as u128) % params.q as u128) as u64) //We pass in u128 so that it doesn't overflow, then we scale and reduce by q
            .collect::<Vec<u64>>();
    
        Polynomial::new(coeffs)
    }
  }
```

=== Opposite polynomial
\
Another "operation" is the one that gives the opposite of a polynomial, as :
\
#align(center)[$Â_k = (-A_k) mod q$]
\
In Rust :
\
#codly(languages: codly-languages)
```rust
impl Polynomial {
    #[inline]
    pub fn opposite(&self, params: &RingParams) -> Self { 
        let q = params.q;
        let coeffs: Vec<u64> = self.coeffs
            .iter()
            .map(|&coeff| ( - (coeff as i128 )).rem_euclid(q as i128) as u64) //We convert into i128s, so that it doesn't underflow, then we reduce it. 
            .collect::<Vec<u64>>();
        Polynomial::new(coeffs)
    }
}
```

=== Polynomial reduction
Another operation is the reduction by a constant. It's noted :
\
#align(center)[$Â_k = A_k mod lambda$]
\
Where $lambda$ is a constant.
In Rust, it is written as :
\
#codly(languages: codly-languages)
```rust
#[inline]
pub fn reduce(&self, constant: u128) -> Polynomial { //Function that reduce the polynomial by a constant (polynomial mod k)
    let new = self.coeffs
        .iter()
        .map(|c| (*c as u128).rem_euclid(constant) as u64) //We consider that the constant is an u128. It is useless, since a polynomial is made of u64s (so that if the constant is greater than the MAX value that an u64 can store, it wouldn't reduce anything) but we keep it for maybe an evolution.
        .collect();
    Polynomial::new(new)
}
```
#pagebreak()
=== Polynomial division (by a constant)
The last operation we'll implement in this section is the division by a constant. We write it at :
#align(center)[$Â_k = (A_k + lambda/2) slash lambda$]
Why ? Because by default, the compilator does $floor.l x slash y floor.r$ when dividing non-floating numbers, and not a rounding as $floor.l x slash y ceil.r$. For example :

#table(
  columns: 3,
  [*Operation*], [*In Maths with rounding*], [*In Rust*],
  [$x slash y$], [$floor.l x slash y ceil.r$], [$floor.l x slash y floor.r$],
  [$ 7 slash 3$], [$floor.l 2,33... ceil.r = 2$], [$floor.l 2,33... floor.r = 2$],
  [$8 slash 3$], [$floor.l 2,66... ceil.r = 3$], [$floor.l 2,66... floor.r = 2$],
)
When we add $lambda slash 2$, we compensate it. For example :
#table(
  columns: 3,
  [*Operation*], [*In Maths with rounding*], [*In Rust*],
  [$(x + y) slash 2 )slash y$], [$floor.l x slash y ceil.r$], [$floor.l x slash y floor.r$],
  [$ (7 + 1) slash 3$], [$floor.l 2,66... ceil.r = 3$], [$floor.l 2,66... floor.r = 2$],
  [$(8 + 1) slash 3$], [$floor.l 3 ceil.r = 3$], [$floor.l 3 floor.r = 3$],
)

So, in Rust, we implement :
#codly(languages: codly-languages)
```rust
#[inline]
pub fn divide_by_constant( 
    &self,
    constant: u128,
    ) -> Polynomial {

    let new = self.coeffs
        .iter()
        .map(|c| {
            let x = (*c as u128 + constant / 2) / constant; 
            x as u64
        })
        .collect();
     Polynomial::new(new)
}
```
#pagebreak()

== How to use the `Polynomial` code ?

In this section, we'll see how to use the code implemented for polynomials.

Prerequisites :
```bash
cargo add simple-ring
```
Then, in  your project :
```Rust
use simple_ring::{Polynomial, RingParams, find_valid_omega};
```

From this, you can use all the methods defined :
#codly(languages: codly-languages)
```rust
let params = RingParams::new(4, 17, find_valid_omega(4, 17));
let mut coeffs = vec![0u64; 4];
coeffs[3] = 8;
let poly1 = Polynomial::new(coeffs);
let poly2 = Polynomial::zeros(4);
let sum = poly1.sum(&params, &poly2);
let mul = poly1.mul(&params, &poly2);
let scaled = poly1.scale(&params, 10);
let divided = poly1.divide_by_constant(2);
let reduced = poly1.reduce(2);
let opposite = poly1.opposite(&params);
//...
```